### ISSUE TITLE
Can't see data events stats/metrics

### ISSUE THREAD

**Issue by olsajiri** [cilium/tetragon#1003]
When running tetragon with metrics ( --metrics-server=:2112)
I can't see any stats about data events, which we clearly posted.

We might be missing support to peg data events (ops.MSG_OP_DATA).

**Comment by swastik959** [comment]
@olsajiri hi I want to work on this isuue can you please guide me about this

**Comment by olsajiri** [comment]
please check:
https://github.com/cilium/tetragon/blob/main/pkg/grpc/tracing/stats.go

and create similar interface for data events and call it within
https://github.com/cilium/tetragon/blob/main/pkg/observer/data.go

need stats for:
  - data event is received (in HandleData)
  - data event is matched (in DataGet)
  - data event is not matched (in DataGet)

**Comment by swastik959** [comment]
@olsajiri I have created a pr please review it

**Comment by SumaiyaSafdar** [comment]
@olsajiri hey, I want to contribute to this issue, I am a complete beginner. Can I get some briefs about this?

**Comment by lambdanis** [comment]
@olsajiri Is this still a problem?

Running a recent build of Tetragon I'm seeing `tetragon_data_events_total` metric.

**Comment by lambdanis** [comment]
I'm closing this issue as `tetragon_data_events_total` metrics seems to be exposed correctly. If there is still a problem with it then feel free to open another issue.
