### ISSUE TITLE
add homebrew formula for tetragon-cli

### ISSUE THREAD

**Issue by rafaribe** [cilium/tetragon#102]
Just like installing `cilium cli` is a breeze on MacOS thanks to the formula, it would be super cool if there was also a formula for tetragon CLI.

**Comment by seeker815** [comment]
@rafaribe @willfindlay  I can help set up homebrew formula if this is still required>

**Comment by mtardy** [comment]
You can now `brew install tetra` 🥳!
See https://github.com/Homebrew/homebrew-core/commit/fb7f1a193653ae761a7619901a975afcdc798b17 or https://github.com/Homebrew/homebrew-core/pull/121642!
