### ISSUE TITLE
test: `TestUprobeCloneThreads` is flaky

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1022]
It looks like `pkg.sensors.tracing.TestUprobeCloneThreads` is flaky. It fails sometimes on various kernel versions. See
- https://github.com/cilium/tetragon/actions/runs/5063158326/jobs/9089625484?pr=1020#step:6:1170
- https://github.com/cilium/tetragon/actions/runs/5063160908/jobs/9089664071?pr=1021#step:6:1173
- https://github.com/cilium/tetragon/actions/runs/5054887831/jobs/9070570239#step:7:1158

Related artifacts:
[tetragon-vmtests-4.19-0-results.zip](https://github.com/cilium/tetragon/files/11552799/tetragon-vmtests-4.19-0-results.zip)
[tetragon-vmtests-5.10-0-results (1).zip](https://github.com/cilium/tetragon/files/11552800/tetragon-vmtests-5.10-0-results.1.zip)
[tetragon-vmtests-5.10-0-results (2).zip](https://github.com/cilium/tetragon/files/11552801/tetragon-vmtests-5.10-0-results.2.zip)

**Comment by tixxdz** [comment]
fixed by https://github.com/cilium/tetragon/pull/1027
