### ISSUE TITLE
Tetragon should support log forwarding

### ISSUE THREAD

**Issue by Sajiyah-Salat** [cilium/tetragon#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I want to send logs from tetragon to specific server. Is this possible? If yes, please help me reach the file. If there isnt any I would like to see this feature coming up in tetragon. 

### Describe the feature you would like

Tetragon could support log forwarding. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrfastab** [comment]
Tetragon uses log collecting tooling for this. Many exists, fluentd, logstash, kafka, ... and so on. I'm going to close this for now as we don't really have any plans to implement this. If you feel strongly about feel free to open it again with some proposals if using one of the existing tooling wont work for some reason?
