### ISSUE TITLE
Make prometheus metric pod label optional

### ISSUE THREAD

**Issue by rayjanoka** [cilium/tetragon#1037]
### Is there an existing issue for this?

No

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Our system has a lot of unique pod names starting and stopping all the time and we found that after a little time (a few days) the cardinality is very high for the `tetragon_events_total` metric due to the `pod` label. I'm seeing 300k unique labels on a single tetragon with a 3-5s scrape time across 70 nodes and crashing prometheus.

```bash
➜ curl localhost:2112/metrics | awk -F\{ '{print$1}' | sort | uniq -c
...
305435 tetragon_events_total
```

### Describe the feature you would like

If the pod label for the `tetragon_events_total` metric was optionally removed that would greatly reduce the cardinality. 

I tried to filter the label out with `droplabel` in the prometheus serviceMonitor `metricRelabelings` but this results in multiple entries with the same set of labels and the values cannot be re-aggregated (added) back together at scrape time.

### Describe your proposed solution

We may be able to set a flag to enable this and send an empty pod name string [here](https://github.com/cilium/tetragon/blob/main/pkg/metrics/eventmetrics/eventmetrics.go#L84), but not sure. I could put something together if it makes sense.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lambdanis** [comment]
@rayjanoka Thanks for creating this issue. Having pod as a label is definitely problematic in many envs.

> We may be able to set a flag to enable this and send an empty pod name string [here](https://github.com/cilium/tetragon/blob/main/pkg/metrics/eventmetrics/eventmetrics.go#L84), but not sure. I could put something together if it makes sense.

Yes, a flag to control the metrics cardinality is a way to go IMO.

What would be nice to have in the future is an option to configure different granularity, e.g. Kubernetes workload (deployment/daemonset/whatev) or `app` label. So I think something like `metrics-granularity` flag with (initial) options `"pod"` or empty would be a good solution.

Feel free to put something together :)
