### ISSUE TITLE
[Query] Does Tetragon support assessing Kata containers?

### ISSUE THREAD

**Issue by DilanUA** [cilium/tetragon#1055]
Hi Folks,

Any good news on $subject? Can runtime monitoring and threat detection of Tetragon work on top of Kata containers?
@kkourt @olsajiri

**Comment by DilanUA** [comment]
Any update on this @kkourt @olsajiri ? Thanks.

**Comment by DilanUA** [comment]
> Hi,
> 
> We have done tests with kata containers, but it's a platform that we do not test regularly. There are some complications with respect to cgroups so certain functionality might not work as expected.

May I know specifically upto which extent that it might support Kata and what might not work as well?

**Comment by jrfastab** [comment]
The primary issue is Kata is running a VM so isolating the kernel and BPF from host will not "see" inside the Kata VM/container. There are a couple deployment options you might take at this point.

First you might argue its a VM we don't "need" to see inside the container. Then you can just run in the host and hook kernel functions that Kata interacts to "see" what the VM is doing. You will not have visilibility into whatever the VM itself does without interacting with the host OS though.

The other option folks have explored in the past is to put a Tetragon agent in the VM itself. Then on a node you would have Tetragon in Kata + Tetragon in Host. Then merge the output for complete system view. There were opens about how to export logs out of Kata in this environment. For example a lightweight gRPC channel would work or just JSON log export through normal tooling.

I'm going to close the issue as its a Query. But if you want feel free to open a feature request.
