### ISSUE TITLE
Add `DeleteTracingPolicy` method to API

### ISSUE THREAD

**Issue by inliquid** [cilium/tetragon#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently it's possible to manage TracingPolicies with CRDs. They can be added or deleted and Tetragon seems to correctly handle both scenarios. In our case, however, preferred way of adding TracingPolicy is using `AddTracingPolicy` method of its API. But there is no `RemoveTracingPolicy` which makes it not possible to handle cases when one policy should be replaced with another. There is `RemoveSensor`, but it has different purpose.

### Describe the feature you would like

I would like to be able to delete added TracingPolicy with  `RemoveTracingPolicy` method.

### Describe your proposed solution

Add required method to API.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkourt** [comment]
There is a DeleteTracingPolicy method: https://github.com/cilium/tetragon/tree/main/api/v1#tetragon-DeleteTracingPolicyRequest.

**Comment by inliquid** [comment]
@kkourt  there are `DeleteTracingPolicyRequest` and `DeleteTracingPolicyResponse` messages, but no API method which makes use of them.

**Comment by inliquid** [comment]
@kkourt thanks, I would like to contribute and implement it. May I send you a DM in Slack in case of some problems?

**Comment by kkourt** [comment]
> @kkourt thanks, I would like to contribute and implement it. May I send you a DM in Slack in case of some problems?

@inliquid  Cool!

I'd prefer keeping the communication public so that other people can contribute / benefit.

**Comment by kkourt** [comment]
Some steps to address this from the top of my head:
 - [ ] add the appropriate method the proto file. See: https://github.com/cilium/tetragon/blob/0f18614fc1aff412aa3ce69016367672ec27fa42/api/v1/tetragon/sensors.proto#L123-L125
 - [ ] run `make codegen` to generate the corresponding code.
 - [ ] The implementation is already https://github.com/cilium/tetragon/blob/b49befb0cf2478341b8accc3c2ae9416cf82a9f0/pkg/server/server.go#L252 so if you use the same name everything should compile
 - [ ] update the cli with this new method. See: https://github.com/cilium/tetragon/blob/main/cmd/tetra/tracingpolicy/tracingpolicy.go#L85

**Comment by kkourt** [comment]
@inliquid :wave: Are you still interested in implementing this?

**Comment by inliquid** [comment]
@kkourt absolutely, was a little bit busy on my main job, but was going to start implementing, your checklist is very well structured and clear, so I hope it won't take a lot of time.

**Comment by kkourt** [comment]
> @kkourt absolutely, was a little bit busy on my main job, but was going to start implementing, your checklist is very well structured and clear, so I hope it won't take a lot of time.

Sounds good! Thanks!
