### ISSUE TITLE
docs: clarify beta status of Tetragon on the docs home page

### ISSUE THREAD

**Issue by lizrice** [cilium/tetragon#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A visitor to the Tetragon site could assume that Tetragon is graduating at the same time as the main Cilium project. They also might not understand the relationship between Cilium & Tetragon. 

There's going to be a link from the Cilium docs to the Tetragon docs ([here's](https://github.com/cilium/cilium.io/pull/295) the PR that's adding it).  As we approach graduated status for Cilium, it's important that visitors don't assume that the Tetragon sub-project has the same maturity level. 

I'd suggest that we add something to the Tetragon home page that says something like: 

* Tetragon is a sub-project under Cilium
* Tetragon is currently at a beta level of maturity (and maybe spell out what that means in terms of stability, likelihood of API/CRD changes, readiness for production use etc) 

 

### Tetragon Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtardy** [comment]
Hey @lizrice, you think we should put it straight on the homepage https://tetragon.cilium.io/? Where would you think it would make sense to add this information, do you have an idea? Like between the paragraph and the getting started button?

**Comment by mtardy** [comment]
Or perhaps, since cilium.io is not linking to the homepage but straight to the doc on this page https://tetragon.cilium.io/docs/, we could put it in overview in the doc?

**Comment by kkourt** [comment]
I think there are two places that we should add this: github repo's README (many, if not most, people will land there), as well as in the docs (https://tetragon.cilium.io/docs/).

**Comment by mtardy** [comment]
> as well as in the docs (https://tetragon.cilium.io/docs/).

Do you think here https://tetragon.cilium.io/docs/overview/ would be appropriate? By the way, I intend to simplify the README drastically when the doc is released to remove the duplicates (but this is the kind of info that would take place in the simplified version).

**Comment by xmulligan** [comment]
One way you could add it to the homepage would be in the bottom corner like Cilium saying something like "Tetragon was originally created by Isovalent and is currently a beta sub-project under Cilium"

<img width="623" alt="Screenshot 2023-07-07 at 12 38 16" src="https://github.com/cilium/tetragon/assets/29048870/0e08ca3c-1c02-41b2-8ec7-24e81d5b0489">

**Comment by xmulligan** [comment]
I think adding it to  https://tetragon.cilium.io/docs/overview/ would also make sense

**Comment by mtardy** [comment]
I guess this no longer applies after Tetragon v1.0, please reopen it if it does!
