### ISSUE TITLE
Let renovatebot update Go toolchain in a single PR

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1169]
See:
- https://github.com/cilium/cilium/issues/24806
- https://github.com/cilium/cilium/pull/24895

This is awesome and we should do it in Tetragon, our Golang versions are inconsistent and this is the ultimate solution.

We have only one task that might be needed before doing that which is getting rid of the cilium-builder image we use in the main Dockerfiles. We use it in this step: https://github.com/cilium/tetragon/blob/be355a8062cab637e6a9a7ec95f8a6b926e73816/Dockerfile#L23C1-L33

And this is an internal image used by Cilium where they have access to the Go information but we don't since the image has not external tags https://github.com/cilium/cilium/blob/438ed82626f9bf0a82c507c2c9faec28509f2b31/images/builder/Dockerfile.

**Comment by AvineshTripathi** [comment]
Would love to take this and start working on it!

**Comment by mtardy** [comment]
> Would love to take this and start working on it!

I was going to take this one eventually but wanted to do a break on renovate stuff so feel free to propose something, I will be happy to help. https://github.com/cilium/cilium/pull/24895 should help you a lot on how to do that.

**Comment by AvineshTripathi** [comment]
After initial explore and trying up renovate what I am understanding is that we have to find all those file in the repo that is not consistent i.e. doesnot have same go version and put it in the renovte to update it right?

Also what would you recommend me best way to find those files that needs change? manually or  some regrex stuff

Please correct me if I am going in wrong direction. Thanks

**Comment by mtardy** [comment]
> After initial explore and trying up renovate what I am understanding is that we have to find all those file in the repo that is not consistent i.e. doesnot have same go version and put it in the renovte to update it right?
> 
> Also what would you recommend me best way to find those files that needs change? manually or some regrex stuff
> 
> Please correct me if I am going in wrong direction. Thanks

So this is not exactly a good first issue for the repository because it's related to maintenance and requires some context over how we build / distribute Tetragon to change all the places where we specify a Go version. This also requires a fairly advanced setup of renovate, so a bit of familiarity with it.

If you really want to work on this specific issue, I can try to help you but it might take a lot of time. Otherwise, if you are not too familiar I would suggest picking up [a good first issue](https://github.com/cilium/tetragon/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), like adding a new tutorial/task to read metrics or load tracing policies for example:
- https://github.com/cilium/tetragon/issues/928
- https://github.com/cilium/tetragon/issues/1229

The first has been stale for two months so I guess it's reasonable if you want to work on that.

**Comment by mtardy** [comment]
> Thanks @mtardy for the response, sure I would step down from the issue to make this issue resolve faster and thanks for issue links

Please if you find anything else in the repository that interests you I would be happy to receive a PR from you. We even discussed this issue this morning offline and found a complication because of an image we use for the build that we don't exactly know how to solve internally, so this might get more complicated than previously thought.
