### ISSUE TITLE
windows binaries are missing the .exe extension

### ISSUE THREAD

**Issue by bakito** [cilium/tetragon#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Windows release artifacts are missing the .exe suffix in the releases tar.gz

All windows binaries should have the .exe suffix.

### Tetragon Version

v0.9.0

### Kernel Version

-

### Kubernetes Version

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtardy** [comment]
Hey thanks for opening the issue, indeed it was missing and we had everything in place to make the fix super easy: https://github.com/cilium/tetragon/pull/1196.
