### ISSUE TITLE
unknown field "returnArgAction" in file_monitoring.yaml

### ISSUE THREAD

**Issue by sn99** [cilium/tetragon#1225]
### What happened?

I have a bare metal install of tetragon and when I run:

`sudo tetra --server-address "unix:///var/run/tetragon/tetragon.sock" tracingpolicy add file_monitoring.yaml`

I get the following error:

`failed to add tracing policy: rpc error: code = Unknown desc = error unmarshaling JSON: while decoding JSON: json: unknown field "returnArgAction"`

### Tetragon Version

server version: v0.9.0
cli version: v0.9.0

### Kernel Version

Linux alfred-windows 5.15.90.1-microsoft-standard-WSL2

**Comment by kkourt** [comment]
Thanks for the report!

I believe this should be fixed by https://github.com/cilium/tetragon/pull/1181.
We released v0.10.0 recently. Could you please check if the issue still exists in the version?

CC: @kevsecurity
