### ISSUE TITLE
Extract kubernetes username within each exec log

### ISSUE THREAD

**Issue by amirnazarizadeh** [cilium/tetragon#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

I want to get kubernetes (or openshift) username of user that executes commands in a pod. How can I do this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-2** [comment]
The discussion around #2030 may be relevant.

**Comment by mtardy** [comment]
Sorry nobody responded directly here, the same discussion happened in another issue later:
- https://github.com/cilium/tetragon/issues/2015

I will close this one to concentrate on things where we have the most context on this, it's not resolved though!
