### ISSUE TITLE
Rework cmds in `/tetra/cmd/tracingpolicy` to return non-0 exit code on failure

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1262]
See more details here https://github.com/cilium/tetragon/pull/1253#discussion_r1270394851.

**Comment by mtardy** [comment]
> Can I work on this please

sure

**Comment by saputkin** [comment]
@clemenkok  hi!
If you are not working on this issue, I would like to work on it :)

**Comment by clemenkok** [comment]
Yes please go ahead
