### ISSUE TITLE
deprecate sensors gRPC interface

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#1272]
The sensors gRPC interface is outdated. We should deprecate it and use tracingpolicies instead. Before deprecating, however, we need to provide the functionality to disable a tracingpolicy as we, currently, do with sensors.

- [x] implement disable tracing policies gRPC call: https://github.com/cilium/tetragon/pull/1562
- [ ] deprecate sensors

**Comment by kkourt** [comment]
In an offline discussion, @mtardy mentioned that:
> disable [a policy] without modifying the resource does not sounds very "declarative"/"k8s" way. I think you can end up in a very confusing situation where you don't understand why you perfectly fine tracing policy does not apply. Having a field in the policy [that allows you to disable it] would make more sense indeed

**Comment by inliquid** [comment]
@kkourt could you please clarify a little bit, does that mean that in order to "disable" policy I will have to delete one and then apply it with some additional field `disabled` set to `true`?

As a side note, I think when it comes to working with policies over gRPC instead of CRD, it's already some sort of not very "k8s way". But at the same it's the reason why we want tot use it, as it's much more flexible.

**Comment by kkourt** [comment]
> @kkourt could you please clarify a little bit, does that mean that in order to "disable" policy I will have to delete one and then apply it with some additional field `disabled` set to `true`?

No. We want to keep a distinction between removing and disabling. The idea would be that you will have a filed in the policy to disable it.

> As a side note, I think when it comes to working with policies over gRPC instead of CRD, it's already some sort of not very "k8s way". But at the same it's the reason why we want to use it, as it's much more flexible.

**Comment by kkourt** [comment]
> > The idea would be that you will have a field in the policy to disable the policy's functionality and then you would just update the k8s resource (without deleting).
> 
> Thanks, the point here is that we are managing `tetragon` through gRPC, and there is no API method to update the policy, only `AddTracingPolicy`, `DeleteTracingPolicy` and `ListTracingPolicies`, so how do I disable a policy it in this case?

I think we would need to add a new gRPC method for that. I haven't thought it through, but I can see two options: (i) having an UpdateTracingPolicy method that you can use to disable a policy or (ii) have a DisableTracingPolicy method.

**Comment by inliquid** [comment]
> (ii) have a DisableTracingPolicy method

That's what I thought of initially.

**Comment by inliquid** [comment]
Yep that would be totally fine.
