### ISSUE TITLE
Make renovate ignore replace directive dependencies

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1326]
See https://github.com/cilium/tetragon/pull/1252#discussion_r1284588057 and https://github.com/cilium/tetragon/pull/1179#discussion_r1284590385. 

Basically we need to add this https://github.com/cilium/cilium/blob/main/.github/renovate.json5#L121-L149.

Apparently, we can also remove the kafka directive.

cc @rolinh @lambdanis 
I'll make the PR no worries but if you can extract a nice list from this https://github.com/cilium/cilium/blob/main/.github/renovate.json5#L121-L149 that we should add given our replace directive that would be truly awesome and if we can cleanup once for good what we need to have and what we can remove.

**Comment by lambdanis** [comment]
As long as Tetragon vendors Cilium, replace directives from [Cilium go.mod](https://github.com/cilium/cilium/blob/v1.14/go.mod#L259-L271) should be replicated in Tetragon go.mod. On 1.14 branch there are four of them. The renovate ignore config should also basically replicate Cilium, just `netlink` is no longer needed there, as it was switched back to upstream in https://github.com/cilium/cilium/commit/9f0be9ecbe735086b7825f2841b9b167b0ccbb02, and I think ginkgo won't be needed in Tetragon config either.

**Comment by mtardy** [comment]
> As long as Tetragon vendors Cilium, replace directives from [Cilium go.mod](https://github.com/cilium/cilium/blob/v1.14/go.mod#L259-L271) should be replicated in Tetragon go.mod. On 1.14 branch there are four of them. The renovate ignore config should also basically replicate Cilium, just `netlink` is no longer needed there, as it was switched back to upstream in [cilium/cilium@9f0be9e](https://github.com/cilium/cilium/commit/9f0be9ecbe735086b7825f2841b9b167b0ccbb02), and I think ginkgo won't be needed in Tetragon config either.

ok I'll try that, maybe client-go will be a bit annoying but we'll see.

**Comment by lambdanis** [comment]
Cilium should ideally be excluded from renovate too, because they might require updating all of these excluded dependencies. I'm not 100% sure about k8s dependencies - maybe renovate could update them automatically only for patch versions?
