### ISSUE TITLE
Is there any way to send container logs to kafka

### ISSUE THREAD

**Issue by nisainan** [cilium/tetragon#137]
or we must need another tool like filebeat or fluentd?

**Comment by kkourt** [comment]
Correct, there is currently no support within tetragon to send container logs to kafka.

**Comment by nisainan** [comment]
I saw some document about hubble in tetragon, maybe we can use hubble to connect tetragon grpc server to show the monitor nicely,but it is not open-source,right?

**Comment by kkourt** [comment]
Closing this issue, as there are no plans to send logs to kafka from Tetragon. We can always reopen it (or create a new one, if need be).

**Comment by kkourt** [comment]
> I saw some document about hubble in tetragon, maybe we can use hubble to connect tetragon grpc server to show the monitor nicely,but it is not open-source,right?

Apologies for the delayed answer, but, as far as I'm aware, this is not possible.
