### ISSUE TITLE
Add common Go & gRPC Prometheus metrics

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Add Prometheus metrics commonly used in Go projects:
- [ ] [Go metrics](https://pkg.go.dev/github.com/prometheus/client_golang@v1.16.0/prometheus/collectors#NewGoCollector) from prometheus/client_golang
- [ ] [process metrics](https://pkg.go.dev/github.com/prometheus/client_golang@v1.16.0/prometheus/collectors#NewProcessCollector) from prometheus/client_golang
- [ ] [gRPC server metrics](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus#ServerMetrics) from go-grpc-middleware
- [ ] `tetragon_build_info` metric - a gauge with constant 1 value labeled with build info

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jack-R-lantern** [comment]
@lambdanis Can you assign it to me?

**Comment by lambdanis** [comment]
@Jack-R-lantern Sure, thanks!
