### ISSUE TITLE
CI: check that the CRD version is updated

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#1412]
For every change in the CRD, we need to update the patch version in: https://github.com/cilium/tetragon/blob/1b454b2640622ed0e9f0c42d0033449d8aee0882/pkg/k8s/apis/cilium.io/v1alpha1/register.go#L18.

Create a GH actions that checks whether there are changes in the CRD and complains if the version was not updated.

**Comment by Jack-R-lantern** [comment]
please assign me

**Comment by kkourt** [comment]
@Jack-R-lantern I just assigned you, thanks.

**Comment by rakshitgondwal** [comment]
Hey @Jack-R-lantern! Are you still working on this?

**Comment by Jack-R-lantern** [comment]
@rakshitgondwal I am not currently doing that, feel free to proceed. Thank you.

**Comment by sadath-12** [comment]
assign me
