### ISSUE TITLE
tetragon: use released clang

### ISSUE THREAD

**Issue by jrfastab** [cilium/tetragon#142]
We currently use an older clang release with BPF backports. This costs us time we have to maintain the clang branch and is now blocking building ARM releases.

[ ] upgrade tooling to use latest released clang
[ ] fixup errors on BPF code paths generated by clang
[ ] tests to ensure doesn't break us again (kernel, nightly, ?)

The reason for the branch was originally because we carried some out of tree fixes/patches. These have been merged upstream for a long time now (1+year) but I never managed to get the code to build on recent release so did a simpler task and backported the BPF backend patches/fixes I needed.

Lets fix this all up as original reason for the backport (extra alu32 patches) is no longer needed.

**Comment by willfindlay** [comment]
@jrfastab Do we still want a tools-install target that installs upstream clang or are we just relying on the user to have the right version of clang installed?

**Comment by willfindlay** [comment]
I've got a partial draft up that I believe covers item (2) for now. https://github.com/cilium/tetragon/pull/145
