### ISSUE TITLE
Support resources object in tetragon.Operator in the Helm Chart

### ISSUE THREAD

**Issue by kskurtveit** [cilium/tetragon#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Yes! I recently installed Tetragon and I encountered an issue with the helm chart not supporting the resources object on the tetragon.Operator. However the tetragon component itself and the hubble-exporter both supports setting the resources object in the charts values-file.

This quickly becomes a problem if you have e.g resourceQuotas in your cluster and or Kyverno in place to make sure quotas are set.

### Describe the feature you would like

Tetragon could support having resources object on the tetragon.Operator by adding this functionality to their helm chart. Right now there is no way to get this if you don't want to change the source of the chart itself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkourt** [comment]
@kskurtveit would be interested in doing a PR to address this issue?

**Comment by kskurtveit** [comment]
Sure thing!
