### ISSUE TITLE
doc: automatically generate the tetragon daemon flags reference

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#1427]
Right now when we add / remove daemon flags , the https://github.com/cilium/tetragon/blob/main/docs/content/en/docs/reference/tetragon-configuration.md#tetragon-controlling-settings is not auto generated, we have to do it manually. 

Reported here: https://cilium.slack.com/archives/C03EV7KJPJ9/p1693863820331569  and see thread for maybe some solutions

**Comment by jrfastab** [comment]
Flags are automatically generated and in docs now https://tetragon.io/docs/reference/tetragon-configuration/

**Comment by jrfastab** [comment]
I'll mark as a release blocker and we either update manually or automate.
