### ISSUE TITLE
tetragon: update libbpf usage to cilium/ebpf or latest version of libbpf

### ISSUE THREAD

**Issue by jrfastab** [cilium/tetragon#143]
We currently run a fairly old libbpf with an extra patch or two to get some functionality we needed. This issue is to update to either cilium/bpf (ideally) or at least run latest libbpf. This will clean up the build infra.

**Comment by sh7dm** [comment]
I'm currently trying to implement it using cilium/ebpf replacing pkg/bpf calls. Ran into a weird issue (on kernel 5.17): 
`LoadPinnedProgram` returns `permission denied` when loading tracing program `bpf/objs/bpf_exit.o`. Of course, running with root.

**Comment by sh7dm** [comment]
Might be somehow related to #164 as I'm using upstream clang-14

**Comment by sh7dm** [comment]
> Might be somehow related to #164 as I'm using upstream clang-14

Irrelevant, copied objs from docker image, that didn't help

**Comment by sh7dm** [comment]
I am on the way porting everything to cilium/ebpf package

**Comment by kkourt** [comment]
@sh7dm cool!

Could you please sync with @olsajiri? He is also working on this.

**Comment by sh7dm** [comment]
Oh, looks like this issue was created after the PR. Will check out #141 .

**Comment by kkourt** [comment]
https://github.com/cilium/tetragon/pull/199
