### ISSUE TITLE
Enrich `GetEventsResponse` with new field `tracing_policy_name`

### ISSUE THREAD

**Issue by inliquid** [cilium/tetragon#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There were some discussions on Slack over the topic, but not sure if they led to some ongoing tasks.

We would like to process incoming (in my case through gRPC interface) Tetragon events differently depending on which TracingPolicy produced the event, f.e. some of them should be saved to DB.

### Describe the feature you would like

I think adding an additional field `tracing_policy_name` to `GetEventsResponse` should solve the issue. Some unclear part here is what should be in there when `process_exec` and `process_exit` events submitted, since they don't belong to any customer policy.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtardy** [comment]
So we have discussed this offline with the team and I think this is of interest, as of now:
- you can use the call name to link an event to a tracingpolicy (or the tracepoint, etc.). I agree it's not the best.
- we can reflect the name in the event.
- we can add an arbitrary field like we do for args' labels.

Thanks for opening this issue :)

**Comment by inliquid** [comment]
> you can use the call name to link an event to a tracingpolicy

Do you mean `function_name` field?

**Comment by jrfastab** [comment]
I think a label fields that gets pushed through the policy to the event makes a lot of sense here.

**Comment by jrfastab** [comment]
I marked this with good first issue tag.
