### ISSUE TITLE
Tetragon on ARM silicon in non-container environments

### ISSUE THREAD

**Issue by lizrice** [cilium/tetragon#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It's not easy to run Tetragon on ARM silicon, in a non-container environment (where you don't have docker/podman installed). For Intel, we have a standalone binary as part of the release - for example [tetragon-v0.11.0-amd64.tar.gz](https://github.com/cilium/tetragon/releases/download/v0.11.0/tetragon-v0.11.0-amd64.tar.gz). Would be nice to have a similar binary built for arm64!

### Describe the feature you would like

Tetragon binary for arm64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tixxdz** [comment]
todo: update doc to note both architectures
