### ISSUE TITLE
vmtests failiures in main branch

### ISSUE THREAD

**Issue by michi-covalent** [cilium/tetragon#1533]
some vm tests are failing in main branch:

### 5.4 kernel: https://github.com/cilium/tetragon/actions/runs/6353568636/job/17258919179

- `pkg.sensors.tracing.TestKprobeValidationListWrongName`
- `pkg.sensors.tracing.TestKprobeValidationListGeneratedFtraceNotEmpty`

### 4.19 kernel: https://github.com/cilium/tetragon/actions/runs/6353568636/job/17258918714

- `pkg.sensors.tracing.TestKprobeValidationListWrongOverride`
- `pkg.sensors.tracing.TestKprobeValidationWrongOverride`

maybe it's related to https://github.com/cilium/tetragon/pull/1508? 💭

**Comment by kkourt** [comment]
This seems to have been fixed. Closing and we can reopen if it appears again.
