### ISSUE TITLE
Unsupported kernel issue

### ISSUE THREAD

**Issue by CaledoniaProject** [cilium/tetragon#154]
The container won't run, what should I do?

```
time="2022-06-11T01:37:21Z" level=fatal msg="Failed to start tetragon" error="tetragon, aborting kernel autodiscovery failed: Kernel version \"3.10.0-1160.62.1.el7.x86_64\" BTF search failed kernel is not included in supported list. Use --btf option to specify BTF path and/or '--kernel' to specify kernel version"
```

**Comment by pchaigno** [comment]
Did you see https://github.com/cilium/tetragon/issues/127?

**Comment by CaledoniaProject** [comment]
@pchaigno Looks like a duplicate issue, but is there any existing kernel RPM package with BTF enabled? Also, can you write a FAQ for this issue?

**Comment by CaledoniaProject** [comment]
By kernel config options, did you mean CONFIG_DEBUG_INFO_BTF? 
https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/

**Comment by CaledoniaProject** [comment]
I've moved to Ubuntu 20.04 which have CONFIG_DEBUG_INFO_BTF enabled by default, case closed.
