### ISSUE TITLE
Slack private token in the tetragon repo

### ISSUE THREAD

**Issue by jedsalazar** [cilium/tetragon#158]
A slack private token seemingly used for build notifications to a #bots channel has been found in the tetragon repo. It's base64 encoded but should probably be encrypted or set to a variable and the credential should be rotated
https://github.com/cilium/tetragon/blob/main/vendor/github.com/go-openapi/analysis/appveyor.yml#L27-L29

**Comment by pchaigno** [comment]
You might want to report it on the original repository: https://github.com/go-openapi/analysis/blob/a935f7372e0b683a49a43fa13495c13c6e839f52/appveyor.yml#L26-L28.

**Comment by pchaigno** [comment]
Closing as I don't think that affects this repository. AppVeyor isn't enabled here.
