### ISSUE TITLE
Cross compiling target arm64 gives: failed to parse platform

### ISSUE THREAD

**Issue by Jiahao0** [cilium/tetragon#1595]
### What happened?

I want to use it in embedded env. I tried cross compiling, but with the following error. Any idea what's wrong? Please help.

`
~/tetragon$ docker build -t 'tetragon' --build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETARCH=arm64 --build-arg 
 BUILDARCH=amd64 - < Dockerfile
`
`
Sending build context to Docker daemon   7.68kB
`
`
Step 1/41 : FROM --platform=$BUILDPLATFORM quay.io/cilium/clang:aeaada5cf60efe8d0e772d032fe3cc2bc613739c@sha256:b440ae7b3591a80ffef8120b2ac99e802bbd31dee10f5f15a48566832ae0866f as bpf-builder
`
`
**failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument**
`
`
~/tetragon$ uname -a
`
`
Linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
`
$ docker version
`
`
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
`

Thanks.

### Tetragon Version

latest

### Kernel Version

NA

### Kubernetes Version

NA

**Comment by mtardy** [comment]
Hello, currently with the Dockerfile you can only cross-arch compile from amd64 to arm64, which is what you are trying to do fortunately. If you want to build an arm64 image on an amd64 build platform, please do the following:

```shell-session
TARGET_ARCH=arm64 make image
```

Feel free to ask if you need custom stuff and help understanding the Makefile!

**Comment by Jiahao0** [comment]
Hi, thanks for the reply. I just tried your suggestion and it finished with success. 
Then I looked for tetragon binary, but with no luck. 
I may not be clear enough before. Actually I want to bare-metal Tetragon, because docker is not available on my dev board.
Any suggestions?

`root@ThinkPad-L14-Gen-1:/data/cjh/tetragon# TARGET_ARCH=arm64 make image
docker build -t "cilium/tetragon:latest" --target release --build-arg TETRAGON_VERSION=v0.12.0-pre.0-231-g02861f05 .
[+] Building 2.5s (35/35) FINISHED                                                                                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                         0.0s
 => => transferring dockerfile: 5.88kB                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                            0.0s
 => => transferring context: 580B                                                                                                                                                            0.0s
 => [internal] load metadata for quay.io/cilium/clang:aeaada5cf60efe8d0e772d032fe3cc2bc613739c@sha256:b440ae7b3591a80ffef8120b2ac99e802bbd31dee10f5f15a48566832ae0866f                       1.2s
 => [internal] load metadata for docker.io/library/golang:1.21.2@sha256:e9ebfe932adeff65af5338236f0b0604c86b143c1bff3e1d0551d8f6196ab5c5                                                     1.8s
 => [internal] load metadata for docker.io/library/golang:1.21.2-alpine@sha256:a76f153cff6a59112777c071b0cde1b6e4691ddc7f172be424228da1bfb7bbda                                              1.8s
 => [internal] load metadata for docker.io/library/alpine:3.18.4@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978                                                     1.9s
 => [gops 1/2] FROM docker.io/library/golang:1.21.2-alpine@sha256:a76f153cff6a59112777c071b0cde1b6e4691ddc7f172be424228da1bfb7bbda                                                           0.0s
 => [base-build 1/7] FROM docker.io/library/alpine:3.18.4@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978                                                            0.0s
 => [internal] load build context                                                                                                                                                            0.4s
 => => transferring context: 1.50MB                                                                                                                                                          0.4s
 => [tetragon-builder 1/6] FROM docker.io/library/golang:1.21.2@sha256:e9ebfe932adeff65af5338236f0b0604c86b143c1bff3e1d0551d8f6196ab5c5                                                      0.0s
 => [bpftool-builder 1/7] FROM quay.io/cilium/clang:aeaada5cf60efe8d0e772d032fe3cc2bc613739c@sha256:b440ae7b3591a80ffef8120b2ac99e802bbd31dee10f5f15a48566832ae0866f                         0.0s
 => CACHED [base-build 2/7] RUN apk add iproute2                                                                                                                                             0.0s
 => CACHED [base-build 3/7] RUN mkdir /var/lib/tetragon/ &&     mkdir -p /etc/tetragon/tetragon.conf.d/ &&     mkdir -p /etc/tetragon/tetragon.tp.d/ &&     apk add --no-cache --update bas  0.0s
 => CACHED [tetragon-builder 2/6] WORKDIR /go/src/github.com/cilium/tetragon                                                                                                                 0.0s
 => CACHED [tetragon-builder 3/6] RUN apt-get update                                                                                                                                         0.0s
 => CACHED [tetragon-builder 4/6] RUN if [ amd64 != amd64 ];     then apt-get install -y libelf-dev zlib1g-dev crossbuild-essential-amd64;     else apt-get install -y libelf-dev zlib1g-de  0.0s
 => CACHED [tetragon-builder 5/6] COPY . ./                                                                                                                                                  0.0s
 => CACHED [tetragon-builder 6/6] RUN if [ amd64 != amd64 ];     then make tetragon-image LOCAL_CLANG=1 VERSION=v0.12.0-pre.0-231-g02861f05 TARGET_ARCH=amd64 CC=aarch64-linux-gnu-gcc;      0.0s
 => CACHED [base-build 4/7] COPY --from=tetragon-builder /go/src/github.com/cilium/tetragon/tetragon /usr/bin/                                                                               0.0s
 => CACHED [base-build 5/7] COPY --from=tetragon-builder /go/src/github.com/cilium/tetragon/tetra /usr/bin/                                                                                  0.0s
 => CACHED [gops 2/2] RUN apk add --no-cache binutils git  && git clone https://github.com/google/gops /go/src/github.com/google/gops  && cd /go/src/github.com/google/gops  && git checkou  0.0s
 => CACHED [base-build 6/7] COPY --from=gops /go/src/github.com/google/gops/gops /usr/bin/                                                                                                   0.0s
 => CACHED [bpf-builder 2/5] WORKDIR /go/src/github.com/cilium/tetragon                                                                                                                      0.0s
 => CACHED [bpf-builder 3/5] RUN apt-get update && apt-get install -y linux-libc-dev                                                                                                         0.0s
 => CACHED [bpf-builder 4/5] COPY . ./                                                                                                                                                       0.0s
 => CACHED [bpf-builder 5/5] RUN make tetragon-bpf LOCAL_CLANG=1 TARGET_ARCH=amd64                                                                                                           0.0s
 => CACHED [base-build 7/7] COPY --from=bpf-builder /go/src/github.com/cilium/tetragon/bpf/objs/*.o /var/lib/tetragon/                                                                       0.0s
 => CACHED [bpftool-builder 2/7] WORKDIR /bpftool                                                                                                                                            0.0s
 => CACHED [bpftool-builder 3/7] RUN if [ amd64 != amd64 ];     then apt-get update && echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse\nd  0.0s
 => CACHED [bpftool-builder 4/7] RUN apt-get update                                                                                                                                          0.0s
 => CACHED [bpftool-builder 5/7] RUN if [ amd64 != amd64 ];     then apt-get install -y curl git llvm gcc pkg-config zlib1g-dev libelf-dev libelf-dev:arm64 libcap-dev:arm64 crossbuild-ess  0.0s
 => CACHED [bpftool-builder 6/7] RUN git clone --recurse-submodules https://github.com/libbpf/bpftool.git . && git checkout b01941c8f7890489f09713348a7d89567538504b                         0.0s
 => CACHED [bpftool-builder 7/7] RUN if [ amd64 != amd64 ];     then make -C src EXTRA_CFLAGS=--static CC=aarch64-linux-gnu-gcc -j $(nproc) && aarch64-linux-gnu-strip src/bpftool;     els  0.0s
 => CACHED [release 1/1] COPY --from=bpftool-builder bpftool/src/bpftool /usr/bin/bpftool                                                                                                    0.0s
 => exporting to image                                                                                                                                                                       0.0s
 => => exporting layers                                                                                                                                                                      0.0s
 => => writing image sha256:3fd65a4da1bbb649a43b13429b725186fb1467202a10e36c871413789f2d5b41                                                                                                 0.0s
 => => naming to docker.io/cilium/tetragon:latest                                                                                                                                            0.0s
Push like this when ready:
docker push cilium/tetragon:latest
root@ThinkPad-L14-Gen-1:/data/cjh/tetragon# ls
api  CODE_OF_CONDUCT.md  Dockerfile               Dockerfile.codegen        Dockerfile.operator  docs      go.sum   MAINTAINERS.md  Makefile.docker  pkg          testdata  Vagrantfile
bpf  contrib             Dockerfile.clang         Dockerfile.dev            Dockerfile.tarball   examples  install  Makefile        netlify.toml     README.md    tests     vendor
cmd  CONTRIBUTING.md     Dockerfile.clang-format  Dockerfile.golangci-lint  Dockerfile.test      go.mod    LICENSE  Makefile.cli    operator         SECURITY.md  tools
root@ThinkPad-L14-Gen-1:/data/cjh/tetragon# find . -name tetragon|xargs file
./api/vendor/github.com/cilium/tetragon:                                               directory
./api/v1/tetragon:                                                                     directory
./vendor/github.com/cilium/tetragon:                                                   directory
./vendor/github.com/cilium/tetragon/api/v1/tetragon:                                   directory
./cmd/tetragon:                                                                        directory
./contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon:                 directory
./contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon: directory
./tests/e2e/install/tetragon:                                                          directory
./install/linux-tarball/usr/local/lib/tetragon:                                        directory`

Thanks.

**Comment by Jiahao0** [comment]
Hi, my mistake, the fomer question could be ignored. After reading the makefile, I found the option. I exec this cmd:
` TARGET_ARCH=arm64 make tarball-release`
A release tarball pkg was generated:
`tetragon-v0.12.0-pre.0-231-g02861f05-arm64.tar.gz`
Problem is the tetragon bin in the pkg is a x86 format file:
```
tetragon/release/tetragon-v0.12.0-pre.0-231-g02861f05-arm64# file usr/local/bin/tetragon 
usr/local/bin/tetragon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=aBI4qFo5c6OSUVZkryYB/XSj4a2HA4SSyxsinTmLi/5vjVt3fZ3x6h7TgtBBOk/YfY1Lxj2eZrq-Ao6y0P3, stripped
```
Am I missing anything?

Thanks.

**Comment by mtardy** [comment]
ah yes, so the `tarball-release` target might not integrate the `TARGET_ARCH` var correctly. Let's ask the author of this @tixxdz, I'm not sure we have cross-compilation for this target.

**Comment by tixxdz** [comment]
> ah yes, so the `tarball-release` target might not integrate the `TARGET_ARCH` var correctly. Let's ask the author of this @tixxdz, I'm not sure we have cross-compilation for this target.

Hmm checking again make tarball does include the TARGET_ARCH, what's happening here is the arm64 build was never added to images including the GOARCH etc,  remember make tarball just does make image, so nothing really special about it

**Comment by inliquid** [comment]
@mtardy may I ask in this issue, as this seems connected. At some point I needed to build an image and it failed, so I'm wondering what a are requirements for a system that would be able to run `make image` target?

I have Mint 20.3 Una (based on Ubuntu 20.04 Focal).
```
$ uname -a
Linux mint-vm 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

There are a lot of compile errors when I try to run `make image`:
![изображение](https://github.com/cilium/tetragon/assets/6797881/e33f53f2-a893-4d1d-b177-dac4df49c989)

This is the same machine I run Tetragon demo environment on (with test pods emulating real workload, etc).

**Comment by mtardy** [comment]
> @mtardy may I ask in this issue, as this seems connected. At some point I needed to build an image and it failed, so I'm wondering what a are requirements for a system that would be able to run `make image` target?
> 
> I have Mint 20.3 Una (based on Ubuntu 20.04 Focal).
> 
> ```
> $ uname -a
> Linux mint-vm 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> There are a lot of compile errors when I try to run `make image`: [...]
> 
> This is the same machine I run Tetragon demo environment on (with test pods emulating real workload, etc).

Not sure I understand why because `make image` essentially just does:
```shell-session
$(CONTAINER_ENGINE) build -t "cilium/tetragon:${DOCKER_IMAGE_TAG}" --target release --build-arg TETRAGON_VERSION=$(VERSION) .
```

So the requirement is an installation with Docker, it's building the main Dockerfile so there's no need for local dependencies.

**Comment by mtardy** [comment]
> Hi, my mistake, the fomer question could be ignored. After reading the makefile, I found the option. I exec this cmd: ` TARGET_ARCH=arm64 make tarball-release` A release tarball pkg was generated: `tetragon-v0.12.0-pre.0-231-g02861f05-arm64.tar.gz` Problem is the tetragon bin in the pkg is a x86 format file:
> 
> ```
> tetragon/release/tetragon-v0.12.0-pre.0-231-g02861f05-arm64# file usr/local/bin/tetragon 
> usr/local/bin/tetragon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=aBI4qFo5c6OSUVZkryYB/XSj4a2HA4SSyxsinTmLi/5vjVt3fZ3x6h7TgtBBOk/YfY1Lxj2eZrq-Ao6y0P3, stripped
> ```
> 
> Am I missing anything?
> 
> Thanks.

So I'm not super familiar with the `tarball` targets, and Djalal is a bit busy at the moment. If you have a valid Go installation and Docker installed, you can easily cross-build the project with:

```shell
TARGET_ARCH=arm64 make tetragon tetra tetragon-bpf
```

You should find the arm64 binaries in the current directory and the BPF compiled progs under `bpf/objs`.

**Comment by inliquid** [comment]
@mtardy 
> So the requirement is an installation with Docker, it's building the main Dockerfile so there's no need for local dependencies.

Thank you, so basically problem is that for some reason image can't be built on that particular system. I will open a separate issue for this.

**Comment by Jiahao0** [comment]
The arm64 bins are generated now. Thanks

**Comment by tixxdz** [comment]
> The arm64 bins are generated now. Thanks

ok thanks @Jiahao0 for the update! I tried to quickly fix this, but there is another bug related to building bpftool, so when I have a chance will fix it.

btw we are going to release 1.0 soon, so an arm tarball will be generated natively.

**Comment by Jiahao0** [comment]
@tixxdz Good to know about the 1.0 release. I'm interested in trying it. May I ask is there approximately a date for this release?

**Comment by mtardy** [comment]
> @tixxdz Good to know about the 1.0 release. I'm interested in trying it. May I ask is there approximately a date for this release?

beginning of November

**Comment by mtardy** [comment]
Hopefully https://github.com/cilium/tetragon/pull/1805 should resolve this issue if you want to cross-compile using the `make tarball` target. Just use `make TARGET_ARCH=arm64 tarball` on an amd64 machine. 

Be sure to have a complete Docker installation with buildx and QEMU available on your system, for buildx a recent Docker is sufficient, for QEMU you can install the `qemu-user-static` package.
