### ISSUE TITLE
New Tetragon logo

### ISSUE THREAD

**Issue by lizrice** [cilium/tetragon#1623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Tetragon really needs a logo that looks great alongside the Cilium logo, with similar styling and colours, but that gives it a symbol of its own (much like Hubble has its own logo)

### Describe your proposed solution

Here's the proposed design
![alpha-back-v](https://github.com/cilium/tetragon/assets/458616/1c836504-cac1-4d6c-9d51-6e720c342861)

* It has the same colour scheme, font, and outline style as the Cilium logo, so they look good together
* Continues the shield theme
* Choice of yellow for the main T colour is a link to eBPF

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jrfastab** [comment]
I like it. I marked it a release blocker for next release. Thanks Liz.

**Comment by mtardy** [comment]
I think all the images are under:

- Favicons: https://github.com/cilium/tetragon/tree/main/docs/static/favicons
- Various images and diagrams with logo: https://github.com/cilium/tetragon/tree/main/docs/static/images
- svgs (logo): https://github.com/cilium/tetragon/tree/main/docs/static/svgs
- logo in content: https://github.com/cilium/tetragon/blob/main/docs/content/en/docs/logo.png
- default Twitter card: https://github.com/cilium/tetragon/blob/main/docs/static/default-twitter-card-image.png
