### ISSUE TITLE
Dead links in the Getting Started section of the README

### ISSUE THREAD

**Issue by paularah** [cilium/tetragon#1653]
There are dead links in the "Getting Started" section of the README. The links probably refer to an older version of the docs. 

I can open a PR for this

**Comment by mtardy** [comment]
hey! Thanks for the PR, I think you submitted your PR locally on your fork, feel free to open a PR against the cilium/tetragon repository and we'll merge it!

**Comment by mtardy** [comment]
Related to https://github.com/cilium/tetragon/issues/1620

**Comment by paularah** [comment]
whoopsie 🫢. That slipped past me.

**Comment by mtardy** [comment]
Thanks a lot for the fix! 🎉 🌮
