### ISSUE TITLE
Minor docs changes for clarifying Tetragon as part of Cilium

### ISSUE THREAD

**Issue by lizrice** [cilium/tetragon#1672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Make it very clear to someone landing on the Tetragon docs that it's a subproject of Cilium 

### Describe your proposed solution

* Change the title on the [overview page](https://tetragon.io/docs/overview/) to "Discover Cilium Tetragon and its capabilities" 
* The footer on the Docs says "Tetragon was originally created by Isovalent" - let's change this to "Cilium Tetragon was originally created by Isovalent"
* The opening on the docs [home/overview page](https://tetragon.io/docs/overview/) starts "Cilium's new Tetragon component" - let's change this to "Cilium's Tetragon component" since it's getting to 1.0 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hacktivist123** [comment]
on it!
