### ISSUE TITLE
docs: add better instructions for module vendoring

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#170]
Folks who are new to Golang might have trouble doing the go mod tidy/vendor/verify dance. It would be nice to provide some better instructions in developer docs to avoid headaches.

**Comment by ADITYADAS1999** [comment]
hey can i work with this issue ? 
I just start learning Golang.🤠

**Comment by mtardy** [comment]
Hey I'm sweeping all good first issue and saw that, sorry you never got a response. I think this could be closed @willfindlay as `make vendor` exists now that does this and is called by `make generate` and `make codegen`. Please reopen if you think we can still improve this.
