### ISSUE TITLE
Is there a grafana dashboard?

### ISSUE THREAD

**Issue by airstring** [cilium/tetragon#1755]
tetragon provides prometheus metrics. So is there a grafana dashboard?

**Comment by mtardy** [comment]
Hey 👋 , I would redirect you to this [discussion thread on Slack](https://cilium.slack.com/archives/C03EV7KJPJ9/p1698922213286869).

Here's a screenshot if you are not on the Cilium Slack (you can join if you want) 
<img width="584" alt="image" src="https://github.com/cilium/tetragon/assets/11256051/c8a0c91b-3445-4c2e-9436-ca282b429ef8">

**Comment by airstring** [comment]
Thank you for your answer.
