### ISSUE TITLE
Add custom annotations and labels to tetragon operator

### ISSUE THREAD

**Issue by vladimirkus** [cilium/tetragon#1761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I encountered a limitation with my ability configuring annotations and labels for the tetragon-operator workload. Currently helm-chart doesn't support custom annotations and labels, however I would like to have this ability, due to the fact that in my infrastructure, I can configure prometheus scraping and log shipment only by adding annotations and labels.

### Describe the feature you would like

I would like to have an ability to add custom annotations and labels to the tetragon-operator pods and deployment, the same as it already implemented for the daemonset pods:
https://github.com/cilium/tetragon/blob/v1.0/install/kubernetes/values.yaml#L8
https://github.com/cilium/tetragon/blob/v1.0/install/kubernetes/values.yaml#L21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkourt** [comment]
Thanks, above make sense to me.


I think the best approach for this would be to:

1. Apply the `podAnnotations` in both the daemonset and the operator deployment pods
2. Have specific annotations for tetragon daemonset set under `tetragon` in the chart (`tetragon.podAnnotations`)
3. Have specific annotations for the operator deployment set under `tetragonOperator` in  chart (`tetragonOperator.podAnnotations`)

Thoughts? Would doing just (1) solve your specific issue?

Also, Would you be interested in implementing this?

Thanks,
Kornilios.
