### ISSUE TITLE
bpf maps:metrics: fix bpf maps metrics

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#1775]
### What happened?

Issues:

1. ~~Reading wrong bpf maps: we add the stats to the maps where it should already have it? this could lead to x_stats_stats~~ https://github.com/cilium/tetragon/blob/3326a78fbb120a9f5946b64733f8786d08be4b0e/pkg/observer/observer_stats.go#L33

2. ~~We fail or return here~~ https://github.com/cilium/tetragon/blob/3326a78fbb120a9f5946b64733f8786d08be4b0e/pkg/observer/observer_stats.go#L37  ~~and I guess we iterate over all maps~~

3. Rename all bpf map stats with "tg_$name_map_stats" schema

### Tetragon Version

master

### Kernel Version

None

**Comment by tpapagian** [comment]
(1) and (2) are fixed by https://github.com/cilium/tetragon/pull/1949

**Comment by lambdanis** [comment]
The bugs here are fixed, so closing the issue. Further improvements to how Tetragon monitors BPF maps (including monitoring more of them) should be done as part of https://github.com/cilium/tetragon/issues/2778
