### ISSUE TITLE
Helm: Expose operator metrics

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#1778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Tetragon Operator exposes some default Prometheus metrics (Go & process) that can be used to monitor its health: https://github.com/cilium/tetragon/blob/3326a78fbb120a9f5946b64733f8786d08be4b0e/operator/cmd/serve/serve.go#L50)

However, the Helm chart doesn't contain a Service exposing the operator metrics port, so if the user wants to scrape the metrics, they have to scrape the pod directly. Let's add support for operator metrics in the Helm chart:
- [x] port in the operator Deployment + a Service exposing it
- [x] Helm value configuring the operator metrics port
- [x] optional ServiceMonitor scraping operator metrics (similar to [this one](https://github.com/cilium/tetragon/blob/a37a56fbb41e094d59c3bd5664a851532ea96e28/install/kubernetes/templates/servicemonitor.yaml) for the agent)
- [ ] Don't start the operator metrics server if `tetragonOperator.prometheus.enabled = false`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hungran** [comment]
I would like to work on this issue

**Comment by lambdanis** [comment]
The first two points were implemented in #1797, there are two other items left. (In the initial issue I wrote `ServiceAccount` instead of `ServiceMonitor`, sorry :woman_facepalming: that was a mistake.)

@hungran If you want to work on them then feel free to open another PR, otherwise they can wait.

**Comment by hungran** [comment]
> The first two points were implemented in #1797, there are two other items left. (In the initial issue I wrote `ServiceAccount` instead of `ServiceMonitor`, sorry 🤦‍♀️ that was a mistake.)

no worries

> @hungran If you want to work on them then feel free to open another PR, otherwise they can wait.

why not :)

**Comment by hungran** [comment]
> Don't start the operator metrics server if tetragonOperator.prometheus.enabled = false

not really get the point on this? this should be a new flag that we can disable at here `operator/cmd/serve/serve.go`

**Comment by lambdanis** [comment]
> > Don't start the operator metrics server if tetragonOperator.prometheus.enabled = false
> 
> @lambdanis not really get the point on this? should be a new flag that we can disable at here `operator/cmd/serve/serve.go`

Good question.
I think we can reuse the `metrics-bind-address` flag - if it's empty then disable the metrics server. Ideally this flag would be passable via a configmap too instead of a CLI argument.

It's all a bit separate issue from the original one, but if you want to implement it too that's great.

**Comment by hungran** [comment]
> > > Don't start the operator metrics server if tetragonOperator.prometheus.enabled = false
> > 
> > 
> > @lambdanis not really get the point on this? should be a new flag that we can disable at here `operator/cmd/serve/serve.go`
> 
> Good question. I think we can reuse the `metrics-bind-address` flag - if it's empty then disable the metrics server. Ideally this flag would be passable via a configmap too instead of a CLI argument.
> 
> It's all a bit separate issue from the original one, but if you want to implement it too that's great.

`tetragonOperator.prometheus.enabled = false` with the logic in args I believed operator metrics server doesn't start right?
https://github.com/hungran/tetragon/blob/main/install/kubernetes/tetragon/templates/operator_deployment.yaml#L36-L41

**Comment by lambdanis** [comment]
Hey, sorry for the delayed response

> `tetragonOperator.prometheus.enabled = false` with the logic in args I believed operator metrics server doesn't start right?
> https://github.com/cilium/tetragon/blob/5f2247c4b677aa3202ea0d0081a02da0f0e75c95/install/kubernetes/tetragon/templates/operator_deployment.yaml#L36-L41
> if yes, this issue might be solved

With `tetragonOperator.prometheus.enabled = false` the metrics server address is not passed explicitly as a flag, but then it's set to the default ":2113":
https://github.com/cilium/tetragon/blob/95974f4ba0029b2f179d49ebf935d7742c42e970/operator/cmd/serve/serve.go#L93
and the metrics server starts on the default port. This should be updated to not start the metrics server at all.

@hungran I'll unassign you from this issue, thanks again for implementing the Helm part! If you want to modify the flags logic then feel free to open a PR, otherwise it remains an open task.

**Comment by yukinakanaka** [comment]
I'd like to contribute to this issue, and I think I found the solution. 😄

- `metricsAddr` is passed to the controller-runtime manager's option here.
https://github.com/cilium/tetragon/blob/4c47837a06f473b45ad189149c63853f2f502304/operator/cmd/serve/serve.go#L50
- According to [the document of controller-runtime](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.18.3/pkg/metrics/server#Options), if `BindAddress` is set to `0`, the metrics server will be disabled.
  >// BindAddress is the bind address for the metrics server.
	// It will be defaulted to ":8080" if unspecified.
	// Set this to "0" to disable the metrics server.
	BindAddress [string](https://pkg.go.dev/builtin#string)

So, setting `0` as the default is a solution to disable the metrics server, like:
```
cmd.Flags().StringVar(&metricsAddr, "metrics-bind-address", "0", "The address the metric endpoint binds to.")
```

**Comment by lambdanis** [comment]
@yukinakanaka Thank you! Sounds good to me, feel free to open a PR.

Since the operator doesn't make sense outside of k8s context, it's fine to disable the metrics server by default and enable it via Helm template.

**Comment by yukinakanaka** [comment]
@lambdanis Thank you for your comment.Yeah, I think so, too!
I made a PR, so PTAL.
