### ISSUE TITLE
btf: kprobe btf id warnings on recent kernels

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#18]
Been seeing a lot of warnings like this on 5.17:
```
time="2022-05-13T15:54:56Z" level=warning msg="invalid or old kprobe spec: failed to dump paramemter type by id: failed to dump btf id 1276"
```

I've attached the BTF file for my kernel here.
[vmlinux.tar.gz](https://github.com/cilium/tetragon/files/8689277/vmlinux.tar.gz)

**Comment by kkourt** [comment]
@willfindlay thanks! Can you also add your config?
