### ISSUE TITLE
Add capability to filter process execution 

### ISSUE THREAD

**Issue by b1shan** [cilium/tetragon#1812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In production environments with high volume of process execution, there is a need to filter processes in-kernel, such as for system namespaces, host, and by the binary name (prefix, postfix, etc). This will improve Tetragon agent performance on Kubernetes clusters with high load by requiring less resources.

More details here: https://cilium.slack.com/archives/C03EV7KJPJ9/p1701113369329629  

### Describe the feature you would like

The Tetragon agent monitors process execution by default. This feature is great, but cannot be customized. What I would like is the ability to provide config options for excluding certain namespaces, host node, and binaries. 

### Describe your proposed solution

The underlying capabilities using selectors, such as matchArgs is good enough for this use case. One option is to load process execution policy as a CRD itself, purely from consistency and UX standpoint. But this isn't a must have.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inliquid** [comment]
Have you tried using filters, they work quite well in our cases with high load clusters. I think if you're using exporter's functionality to export events as logs (either tetragon.log or stdout via `export-stdout` container) it can be configured with config files / config maps / helm values. In case you're using gRPC it's done with `allow_list`/`deny_list` parameters within [GetEventsRequest](https://github.com/cilium/tetragon/blob/main/api/v1/tetragon/events.proto#L77). We also didn't notice any significant overhead when Tetragon is filtering not needed events with this mechanism.

**Comment by b1shan** [comment]
@inliquid thanks for sharing your experience in production. We are in the very early stages with Tetragon. Let me give this a shot and see how it fares.

**Comment by b1shan** [comment]
I am closing this issue. I am not noticing any perf issues that I was anticipating in regards to need for in kernel process filtering.
