### ISSUE TITLE
docs: generated page displayed in section `/docs/reference/`

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1839]
cc @lambdanis 

The generated page injected into https://tetragon.io/docs/reference/tetragon-configuration/ is visible in https://tetragon.io/docs/reference/. It could be done like the other page where it's straight injected into the Markdown at creation without an intermediate page.

**Comment by lambdanis** [comment]
Is there a way to have it as a separate file, but not a separate docs page? I thought that maybe it can be hidden from the TOC by something like `hide_summary: true` ([docs](https://www.docsy.dev/docs/adding-content/navigation/#section-menu)), but then I ended up with `hide_summary: true` being the title of the embedded page :) So I guess that would require a different way of embedding.
![Screenshot from 2023-12-05 22-15-23](https://github.com/cilium/tetragon/assets/3199463/98a1095d-faac-403d-b403-1faf74e202bd)
