### ISSUE TITLE
Improve local k8s developer experience

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#1849]
The current state of the local k8s devexp is the following:
* [contrib/localdev](https://github.com/cilium/tetragon/blob/7c7cb636d23b7c35cdff30940e3f16f01a64d25b/contrib/localdev) directory contains scripts for running a local Kind cluster and installing Tetragon in it
* [Development setup](https://tetragon.io/docs/contribution-guide/development-setup/#running-tetragon-in-kind) docs page explains how to use these scripts and also has some instructions for Minikube

The commands in the docs seem a bit complicated and they don't cover anything apart from the basic installation (for example passing custom Helm values). I'm not sure if Minikube instructions are useful at all.

To make local k8s development easier I suggest to:
- [ ] Introduce Makefile rules for easy local development in Kind. Maybe the [Cilium setup](https://github.com/cilium/cilium/blob/main/Makefile) (and [docs](https://docs.cilium.io/en/latest/contributing/development/dev_setup/)) can be some inspiration.
- [ ] Update dev docs to use Makefile rules and cover a bit more advanced options. Remove Minikube instructions if nobody needs them.

Somewhat related: #1847

**Comment by sadath-12** [comment]
assign me

**Comment by sadath-12** [comment]
I agree with removing minikube . Its just too overloaded in every aspects from kind no reason to use it over kind
