### ISSUE TITLE
policyfilter: add a label that allows to filter based on namespaces

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#1854]
Allow policy pod-label filters to use a label depicting the namespace of the pod (e.g., `k8s:io.kubernetes.pod.namespace`).
This would allow more flexibility to filter policy application than namespaced policies (e.g., `k8s:io.kubernetes.pod.namespace NOT IN [noisy_namespaces]`)

**Comment by sadath-12** [comment]
assign me
