### ISSUE TITLE
Refactor Go event structs to avoid deep copies

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#1857]
On the way from the datapath to the user interface, Tetragon events go trough a few Go structs. This involves copying all data, what negatively impacts the agent performance. Let's investigate if we can improve performance and simplify the userspace code by getting rid of some of these deep copies. Maybe we could remove some of these structs or at least embed a pointer to another struct instead of copying all fields.

An example of that are [MsgExecveEvent](https://github.com/cilium/tetragon/blob/662702a52d7987face1e3795a69d0aa67fe48a2f/pkg/api/processapi/processapi.go#L102) and [MsgExecveEventUnix](https://github.com/cilium/tetragon/blob/662702a52d7987face1e3795a69d0aa67fe48a2f/pkg/api/processapi/processapi.go#L113) in `pkg/api/processapi`. `MsgExecveEvent` corresponds to [msg_execve_event](https://github.com/cilium/tetragon/blob/662702a52d7987face1e3795a69d0aa67fe48a2f/bpf/lib/process.h#L273) BPF struct and it's where the event is copied directly from the datapath. Then in `pkg/sensors/exec` it gets [translated](https://github.com/cilium/tetragon/blob/662702a52d7987face1e3795a69d0aa67fe48a2f/pkg/sensors/exec/exec.go#L28) into a very similar `MsgExecveEventUnix`.

**Comment by kevsecurity** [comment]
#2009 addresses this.
