### ISSUE TITLE
ci: segmentation fault at the generate sbom ci job

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#1894]
### What happened?

Ci fails from time to time at `Generate SBOM` https://github.com/cilium/tetragon/blob/main/.github/workflows/build-images-ci.yml#L131 with:

```
Run bom generate --format json -o sbom_ci_pr_tetragon_00a3f6a2d6f305dca9a09e9ce09a2818e02c3502.spdx \
level=info msg="bom v0.5.1: Generating SPDX Bill of Materials"
level=info msg="Processing directory ."
level=info msg="Loading license data from downloader"
level=info msg="Using embedded v3.20 license list"
level=info msg="Got 536 licenses from downloader"
level=info msg="Writing license data to /tmp/spdx/downloadCache"
level=info msg="Writing 536 SPDX licenses to /tmp/spdx/licenses"
level=info msg="Applying 29 ignore patterns to list of 16080 filenames"
level=info msg="Scanning 15752 files and adding them to the SPDX package"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x894aeb]

goroutine 690 [running]:
sigs.k8s.io/bom/pkg/spdx.(*spdxDefaultImplementation).PackageFromDirectory.func1({0xc0002511c0, 0x31}, 0xc00c8fd1e0)
	/home/runner/go/pkg/mod/sigs.k8s.io/bom@v0.5.1/pkg/spdx/implementation.go:1032 +0x34b
created by sigs.k8s.io/bom/pkg/spdx.(*spdxDefaultImplementation).PackageFromDirectory in goroutine 1
	/home/runner/go/pkg/mod/sigs.k8s.io/bom@v0.5.1/pkg/spdx/implementation.go:1047 +0x92f
Error: Process completed with exit code 2.
```

We have multiple ci steps named: Generate SBOM.

An example of run: [example](https://github.com/cilium/tetragon/actions/runs/7446084163/job/20255633711?pr=1942).

### Tetragon Version

upstream

### Kernel Version

none

**Comment by mtardy** [comment]
I took a look into that, one simple solution would be to stop generating SBOM for CI images but this would hide the issue and this can again appear when it's critical and we want to generate main CI images or release images.

It cannot be solved just by bumping the version of bom since we are using the latest release. I will open an issue against the [kubernetes-sigs/bom](https://github.com/kubernetes-sigs/bom) repo.
