### ISSUE TITLE
bpf: replace arch-specific pt_regs assumptions with bpf co-re macros

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#190]
Our eBPF code makes some arch-specific assumptions about the layout of struct pt_regs. We need to refactor this to use BPF CO-RE macros to make multi-arch support work properly for our kprobes.

**Comment by Forsworns** [comment]
In fact, the problem not only exists in `pt_regs`, e.g. the `sock_common` in
https://github.com/cilium/tetragon/blob/735c3dd6dba5b7a068cf29cd37d603cb8c0c2058/bpf/process/types/sock.h#L25

and `task_struct` in

https://github.com/cilium/tetragon/blob/735c3dd6dba5b7a068cf29cd37d603cb8c0c2058/bpf/process/bpf_process_event.h#L18

Do we need to replace calls `probe_read` to `bpf_core_read`? 

Or simply revise the macro for `probe_read` in

https://github.com/cilium/tetragon/blob/735c3dd6dba5b7a068cf29cd37d603cb8c0c2058/bpf/include/api.h#L206

I think the later one is more convenient but may make codes ambiguous

**Comment by Forsworns** [comment]
Moreover, in the 

https://github.com/cilium/tetragon/blob/735c3dd6dba5b7a068cf29cd37d603cb8c0c2058/bpf/process/bpf_process_event.h#L545

It seems that `nsproxy`, `net_ns` and `kn` are unnecessary, they can be removed by `BPF_CORE_READ` or `BPF_CORE_READ_INTO` macro

**Comment by Forsworns** [comment]
I'll check it tomorrow, it's too late in my timezone now :) I guess a `bpf_core_field_exists()` may be enough. 

BTW, how do you think of replacing customized `_()` to explicit core signatures in the PR above... I don't know if it is better

**Comment by jrfastab** [comment]
I'm a bit partial to _() because I'm used to it. I think fixing the pt_regs so it works correctly on ARM should be done first. I can probably dig up the bpf macros to find the arch.

**Comment by vincentmli** [comment]
@jrfastab 

I guess you mean pt_regs that is only specific to x86 here https://github.com/cilium/tetragon/blob/main/bpf/process/generic_calls.h#L102-L118 ?

```
	if (config->syscall) {
		struct pt_regs *_ctx;
		_ctx = (struct pt_regs *)ctx->di;
		if (!_ctx)
			return 0;
		probe_read(&e->a0, sizeof(e->a0), &_ctx->di);
		probe_read(&e->a1, sizeof(e->a1), &_ctx->si);
		probe_read(&e->a2, sizeof(e->a2), &_ctx->dx);
		probe_read(&e->a3, sizeof(e->a3), &_ctx->r10);
		probe_read(&e->a4, sizeof(e->a4), &_ctx->r8);
	} else {
		e->a0 = ctx->di;
		e->a1 = ctx->si;
		e->a2 = ctx->dx;
		e->a3 = ctx->cx;
		e->a4 = ctx->r8;
	}
```

**Comment by vincentmli** [comment]
> I'm a bit partial to _() because I'm used to it. I think fixing the pt_regs so it works correctly on ARM should be done first. I can probably dig up the bpf macros to find the arch.

@jrfastab  you mean these macros 
https://github.com/torvalds/linux/blob/master/tools/lib/bpf/bpf_tracing.h ? is it simple as  include the `bpf_tracing.h` and include an arm64 vmlinux.h ?  like similar to pwru arm64 support? https://github.com/cilium/pwru/commit/303ea8d89d18c4810c220c85b6e8cb8c7818c508

**Comment by Forsworns** [comment]
@vincentmli yes! that's what I did in the #209

**Comment by kkourt** [comment]
Are there any other known places that we should use the CO-RE macros, or can we close this issue?

**Comment by mtardy** [comment]
For me, this thing is done, otherwise, the arm64 progs would not compile! :)
