### ISSUE TITLE
Release 1.0.1 is missing binaries

### ISSUE THREAD

**Issue by nicholasdille** [cilium/tetragon#1901]
### What happened?

The release does not have pre-compiled binaries while the documentation states otherwise

### Tetragon Version

1.0.1

### Kernel Version

none

**Comment by kkourt** [comment]
Thanks for reporting this.

Please find the binaries here: https://github.com/cilium/tetragon/releases/tag/v1.0.1.

**Comment by mtardy** [comment]
Interestingly we detected that https://github.com/cilium/tetragon/issues/1900 also! I am closing this as this should be resolved, feel free to reopen it if you still have related issues! :) Thanks!
