### ISSUE TITLE
ci: known "Unable to download and extract artifact: Request timeout" issue in vmtests

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1927]
We are subject to this issue https://github.com/actions/download-artifact/issues/249, I guess it will get fixed in a future update.

Examples: [here](https://github.com/cilium/tetragon/actions/runs/7400671018/job/20134998707?pr=1926) or [there](https://github.com/cilium/tetragon/actions/runs/7400671018/job/20134998293?pr=1926).

**Comment by mtardy** [comment]
See https://github.com/cilium/tetragon/pull/1942

**Comment by kkourt** [comment]
@mtardy can we close this?

**Comment by mtardy** [comment]
> @mtardy can we close this?

I'm a bit dissatisfied with the fix, like this user: https://github.com/actions/download-artifact/issues/249#issuecomment-1885250544 but yes we should be able to update to v4 now. I'll close this when I merge the deps bump.
