### ISSUE TITLE
Add a PR template to this repo

### ISSUE THREAD

**Issue by sadath-12** [cilium/tetragon#1929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature you would like

Consider adding a pr template that motivates the contributer to give sufficient information on the work he has done on that pr so anyone could get the proper context on that pr

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lambdanis** [comment]
It would be very useful to add a PR template indeed.

I think it can be inspired by the [Cilium PR template](https://github.com/cilium/cilium/blob/main/.github/pull_request_template.md), maybe a bit simpler. Things that should be mentioned IMO:
* tests (link do dev docs how to run them?)
* commit subject, body and sign-off (link to the Cilium dev docs?)
* release note (if PR title is not enough)
* Add yourself to users (in cilium/cilium repo)

@paularah Any thoughts here?

**Comment by paularah** [comment]
Indeed it'd be useful. We should be have the USERS.md file in soon, once we've gathered the info we need from users. 
@sadath-12 Feel free to open PR if you'd love to take a stab at this.
