### ISSUE TITLE
tetragon does not error out when we track unknown pod events

### ISSUE THREAD

**Issue by sadath-12** [cilium/tetragon#1964]
### What happened?

when we want to monitor some pod events like ``` kubectl exec -ti -n kube-system ds/tetragon -c tetragon -- tetra getevents -o compact --pods doesntexist``` it starts to monitor something even though ```doesntexist``` pod does not exist

### Tetragon Version

CLI version: v1.0.1

### Kernel Version

5.15.137.3-microsoft-standard-WSL2

**Comment by inliquid** [comment]
This is just how a filter works, so from above example, no events will be shown unless there are some pods which name matches regexp "doesntexist". But this may happen at any point in time and client doesn't have to know which pods exist and which don't. I would say this is by intent and quite clear and doesn't need to be changed. Same goes for namespaces, binaries, etc.

**Comment by sadath-12** [comment]
oh fine thanks @inliquid
