### ISSUE TITLE
doc: improve troubleshooting Tetragon

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#1974]
Improve troubleshooting Tetragon

- [x] Unify https://tetragon.io/docs/tutorials/debugging-tetragon/ into https://tetragon.io/docs/troubleshooting/
- [x] Improve doc around tetra bugtool, demo how to run it for all different installation k8s, container or systemd host installation.
- [ ] Add example how to activate gops server for all installation k8s if not by default, but also container or systemd
- [ ] Add example how to activate metrics for all installation if it is not already there.

**Comment by janvi01** [comment]
Hey @tixxdz I would like to work on this issue if there is no update from the assignee.

**Comment by UtkarshUmre** [comment]
Hey @janvi01  I'm actively working on this matter. I initially began the task, but it got sidelined due to exams and other obligations. Nonetheless, I'm back on track and giving it my full attention. If you're genuinely interested in contributing to it, we can collaborate on this

**Comment by janvi01** [comment]
@UtkarshUmre You can open your PR, then I can add my inputs
