### ISSUE TITLE
Migrate e2e labels test from `isovalent/jobs-app`

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1976]
The e2e labels test is suffering from flakes because the jobs-app sometimes fails to deploy, even though we provide enough resources, see https://github.com/cilium/tetragon/issues/1954. The idea would be to migrate from these deployments to something more lightweight and maintained to make this faster and more reliable (thus fix https://github.com/cilium/tetragon/issues/1954).

Our initial idea is to use ~~Google's microservices demo "Online Boutique" https://github.com/GoogleCloudPlatform/microservices-demo (this one doesn't deploy on arm64)~~ OpenTelemetry demo https://github.com/open-telemetry/opentelemetry-demo with the minimal footprint possible. 

The whole e2e labels test (https://github.com/cilium/tetragon/blob/main/tests/e2e/tests/labels/labels_test.go) will need to be adapted first by changing the Helm chart to be deployed:
https://github.com/cilium/tetragon/blob/004d9cfe1982614fa4e83a2e55edea2a20f37b56/tests/e2e/tests/labels/labels_test.go#L45-L49

And especially, the checkers, to suit the new deployments' labels:
https://github.com/cilium/tetragon/blob/004d9cfe1982614fa4e83a2e55edea2a20f37b56/tests/e2e/tests/labels/labels_test.go#L121-L184

**Comment by prateek041** [comment]
Hey @mtardy what is the estimated deadline to resolve this issue ?

**Comment by mtardy** [comment]
Hey, there is no deadline to resolve this issue.

**Comment by prateek041** [comment]
Ok then, I'm gonna give this a shot. Assigning it to myself.

**Comment by mtardy** [comment]
This is the detailed issue @jrfastab

**Comment by rajesh-sampathrajan** [comment]
Hi  @mtardy , looks like this issue is still open?. If yes, may I pick up this issue?, please let me know

**Comment by rajesamp** [comment]
working on resolving `undefined: unix.CBitFieldMaskBit34` -> even after upgrading sys/unix package to .18 and mod vendor, issue still exists.
