### ISSUE TITLE
operator: add a flag to force replacing the CRDs

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#2014]
Currently, the operator will only update the CRD if the running version is smaller than the current version:
https://github.com/cilium/tetragon/blob/c1d6f115ef2eb86d18cac09625f42bec09f0660a/pkg/k8s/crdutils/register.go#L208 

In some cases, however we need to force the operator to replace the CRD version. Add a flag to the operator that allows us to install the current CRD version no matter what the running version is.

**Comment by aohoyd** [comment]
I can handle this.

I see two options here:
1. Adding the new flag `force bool` to https://github.com/cilium/tetragon/blob/c1d6f115ef2eb86d18cac09625f42bec09f0660a/pkg/k8s/crdutils/register.go#L71. This one is breaking pkg's API and I dont know is this acceptable for you
2. Adding the new label, something like
```go
CustomResourceDefinitionSchemaOptionForceReplaceKey = ciliumio.GroupName + ".k8s.crd.schema.option.force-replace"
```
to https://github.com/cilium/tetragon/blob/c1d6f115ef2eb86d18cac09625f42bec09f0660a/pkg/k8s/crdutils/register.go#L33. This one is more implicit than the first, but it saves backward compatibility for the library.

Which one do you think works better?

**Comment by kkourt** [comment]
I think there is a middle ground: introduce a new function `RegisterCRDsWithOptions()` and pass the options there. This does not break compatibility. `RegisterCRD` can be marked as deprecated, and eventually removed.

WDYT?

**Comment by aohoyd** [comment]
As I promised: #2023
