### ISSUE TITLE
validation: improve error message when failing to load a TracingPolicy

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#2022]
Users are faced with this message if they load a TracingPolicy that fails to satisfy the basics of metadata:
```
level=fatal msg="Failed to start tetragon" error="could not find validator for: /, Kind="
```
Tetragon tries to find a validator for an empty `Kind` since it's not specified if the file is empty by mistake for example.

This could be improved by adding some context while returning the error to the callers to emphasize that the issue is a tracing policy file that is invalid.

### Ideas

I see mainly here:
https://github.com/cilium/tetragon/blob/6644bbd6f7165731c9829e718f867c48f17c54a9/pkg/tracingpolicy/generictracingpolicy.go#L285-L291

Where we could do something like this:
```diff
policy, err := os.ReadFile(path) 
if err != nil { 
	return nil, err 
} 
- FromYAML(string(policy))
+ tp, err := FromYAML(string(policy))
+ if err != nil {
+    return nil, fmt.Errorf("failed loading tracing policy file %q: %w", path, err)
+ }
+ return tp, nil
```

You could also add more context here, but I'm not sure if you need it (it would not have helped in the empty file case).
https://github.com/cilium/tetragon/blob/6644bbd6f7165731c9829e718f867c48f17c54a9/pkg/tracingpolicy/generictracingpolicy.go#L273-L276
```diff
validationResult, err := ValidateCRD(policy)
if err != nil {
- 	return nil, err
+ 	return nil, fmt.Errorf("failed to validate policy %q: %w", policy.GetMetadata().Name, err)
}
```

**Comment by mtardy** [comment]
This is the result of a conversation with @christian-2 on the [Cilium OSS slack tetragon channel](https://cilium.slack.com/archives/C03EV7KJPJ9/p1706181969492489). This user would like to work on this :)

Welcome and feel free to take a look at the [contribution guide](https://tetragon.io/docs/contribution-guide/) for help.

**Comment by bishal7679** [comment]
Hello @mtardy @christian-2 I am new here in this project and exploring!
If you don't mind can I work on it as it would be my first contribution
would be highly helpful

**Comment by christian-2** [comment]
@bishal7679 as you can see above I'm in the same position as yourself and besides I already started working on the issue in terms of preparing my environment. So please choose another [good first issue](https://github.com/cilium/tetragon/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), many are available. Thanks.
