### ISSUE TITLE
Helm chart 1.0.2 only has charts.yaml updated. Values file still has 1.0.1 image tags

### ISSUE THREAD

**Issue by wthrbtn** [cilium/tetragon#2061]
### What happened?

Upgraded from 1.0.1 to 1.0.2 using Helm but the tetragon and tetragon-operator images stayed at 1.0.1

Compared the two helm charts and the only difference is in the charts.yaml file. The values.yaml still has 1.0.1 image tags

### Tetragon Version

1.0.1 / 1.0.2

### Kernel Version

5.15 and 6.5

### Kubernetes Version

1.27.9

**Comment by kkourt** [comment]
Thanks for the report. I believe this should have been fixed now (https://github.com/cilium/tetragon/blob/eaa59471c3e963c3c957e726b320079300496c61/install/kubernetes/tetragon/values.yaml#L226) by https://github.com/cilium/tetragon/pull/1993 but we need to ensure that the next release includes the latest images and the next release the release script will do the right thing: https://github.com/cilium/tetragon/blob/eaa59471c3e963c3c957e726b320079300496c61/contrib/update-helm-chart.sh#L20.
