### ISSUE TITLE
The demo app image (json-mock) point to wrong architecture

### ISSUE THREAD

**Issue by hazelnutsgz** [cilium/tetragon#2083]
### What happened?

I am trying to deploy the application demo on arm64 VM following the official page  https://tetragon.io/docs/getting-started/install-k8s/#deploy-demo-application, the `xwing` and` tiefighter ` pod can not start successfully. 

The log of the 2 pods are:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

I tried to download the image` json-mock` behind these two pods, it can work.

I think one way to solve it is specify the ARCH in https://raw.githubusercontent.com/cilium/cilium/v1.15.0-pre.1/examples/minikube/http-sw-app.yaml

### Tetragon Version

1.15.0

### Kernel Version

5.15.50

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:39:59Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/arm64"}

**Comment by mtardy** [comment]
Thanks for the report!


I haven't looked into this but I guess the images used here are not multi-arch and might only run on x86. The next step would be to look into the images used here and see if we can make them multi-arch.

**Comment by mtardy** [comment]
I think it was fixed by those two PRs:
- https://github.com/cilium/cilium/pull/31373
- https://github.com/cilium/tetragon/pull/2311

Feel free to reopen if it's not the case.
