### ISSUE TITLE
ci:test: failure at the post-test job

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#2156]
Some PRs are only failing with a message:
```
Run geekyeggo/delete-artifact@65041433121f7239077fa20be14c0690f70569de
  with:
    token: ***
    name: tetragon-build
    useGlob: true
    failOnError: true
Error: HttpError: Resource not accessible by integration
```
Example: https://github.com/cilium/tetragon/actions/runs/8054418181/job/22019023038?pr=2144

**Comment by mtardy** [comment]
yep we have an issue here https://github.com/cilium/tetragon/issues/2010.

**Comment by mtardy** [comment]
I'm going to close this one since we already have one! :)
