### ISSUE TITLE
Don't give operator permissions to create CRDs if not needed

### ISSUE THREAD

**Issue by lambdanis** [cilium/tetragon#2226]
Tetragon Operator has an option to [skip CRD creation](https://github.com/cilium/tetragon/blob/31117d0596337b6219360ae813ae3c9393991a52/install/kubernetes/tetragon/values.yaml#L233), but even if it's used, the operator ClusterRole still contains [permissions to create CRDs](https://github.com/cilium/tetragon/blob/main/install/kubernetes/tetragon/templates/operator_clusterrole.yaml#L29-L34). For slightly better security hygiene, these permissions can be included conditionally, only if needed.

**Comment by itsCheithanya** [comment]
I would like to contribute to this issue, can you guide me on how to get started

**Comment by lambdanis** [comment]
@itsCheithanya Thanks! To implement the fix, you'll need to use the [Helm if block](https://helm.sh/docs/chart_template_guide/control_structures/#ifelse) in the [operator ClusterRole](https://github.com/cilium/tetragon/blob/main/install/kubernetes/tetragon/templates/operator_clusterrole.yaml#L29-L34). It should be a pretty small change.

To test it, first create a local [kind](https://kind.sigs.k8s.io/) cluster:
```
./contrib/localdev/bootstrap-kind-cluster.sh
```
then create a local `values.yaml` file with CRD creation disabled:
```yaml
tetragonOperator:
  skipCRDCreation: true
```
and install Tetragon with using local Helm chart and your values.yaml file:
```
./contrib/localdev/install-tetragon.sh --values values.yaml
```

Then, check the operator ClusterRole using kubectl:
```
kubectl get clusterrole tetragon-operator -oyaml
```

I hope this gives you a starting point.
