### ISSUE TITLE
May I ask how to exclude the monitoring of some common command processes, such as ls, ssh, grep, which do not record logs

### ISSUE THREAD

**Issue by devops-utils-tools** [cilium/tetragon#2247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

May I ask how to exclude the monitoring of some common command processes, such as ls, ssh, grep, which do not record logs

### Describe the feature you would like

May I ask how to exclude the monitoring of some common command processes, such as ls, ssh, grep, which do not record logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkourt** [comment]
Hi, 

We have a generic way of filtering events: [FiledFlters](https://tetragon.io/docs/reference/grpc-api/#fieldfilter). You can use that to filter out specific command processes.

You can set them when deploying with helm via the `tetragon.fieldFilters` value.

**Comment by devops-utils-tools** [comment]
Can you give me the complete configuration file? Thank you.

**Comment by devops-utils-tools** [comment]
> 你好，
> 
> 我们有一种过滤事件的通用方法：[FiledFlters](https://tetragon.io/docs/reference/grpc-api/#fieldfilter)。您可以使用它来过滤掉特定的命令进程。
> 
> 您可以在使用 helm 部署时通过`tetragon.fieldFilters`值来设置它们。



> 你好，
> 
> 我们有一种过滤事件的通用方法：[FiledFlters](https://tetragon.io/docs/reference/grpc-api/#fieldfilter)。您可以使用它来过滤掉特定的帐户进程。
> 
> 您可以在使用 helm 部署时Can you give me the complete configuration file? Thank you.
通过`tetragon.fieldFilters`值来设置它们。

**Comment by mtardy** [comment]
This should help https://github.com/cilium/tetragon/pull/2249
