### ISSUE TITLE
The wrong version was released in v1.0.2

### ISSUE THREAD

**Issue by ShadowUser17** [cilium/tetragon#2250]
### What happened?

The helm chart of release 1.0.2 contains the previous release!
Compare files between releases 1.0.1 and 1.0.2

### Tetragon Version

v1.0.2

### Kernel Version

Linux k3s 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Kubernetes Version

v1.27.11+k3s1

### Anything else?

v1.0.1 https://github.com/cilium/tetragon/tree/a6b99ba320a76bc88f2f36f4b3f5830adb1223a3/install/kubernetes
v1.0.2 https://github.com/cilium/tetragon/tree/c70b388d6f2edf819b95469efd47c83ed880764d/install/kubernetes

**Comment by mtardy** [comment]
Hello, thanks for the report, indeed it seems there's a mistake here, the release checklist was not done completely in https://github.com/cilium/tetragon/issues/1997.

You can edit that tag manually but a good idea might be for us to release a fixed `v1.0.3` with the correct tag in the helm chart.

**Comment by mtardy** [comment]
We will release `v1.0.3` and that should solve your issue. See https://github.com/cilium/tetragon/issues/2253.

**Comment by ShadowUser17** [comment]
Thank you! I close this issue.

**Comment by mtardy** [comment]
sorry for the delay, we were missing a backport, once https://github.com/cilium/tetragon/pull/2314 is merged, I'll finally do the release.
