### ISSUE TITLE
Could not find Cgroup RKE2 Kubernetes cluster

### ISSUE THREAD

**Issue by didlawowo** [cilium/tetragon#2277]
### What happened?

all pods responding same values

installing tetragon without anyconfig inside RKE2 cluster x86 in kube-system namespace with argocd

### Tetragon Version

1.0.2

### Kernel Version

   Kernel Version:             5.15.0-101-generic                                                                                                               
  OS Image:                   Ubuntu 22.04.4 LTS                                                                                                                
  Operating System:           linux                                                                                                                             
  Architecture:               amd64                                                                                                                              
  Container Runtime Version:  containerd://1.7.11-k3s2                                                                                                           
  Kubelet Version:            v1.27.12+rke2r1                                                                                                                    
  Kube-Proxy Version:         v1.27.12+rke2r1  

### Kubernetes Version

1.27 rke2

### Bugtool

bugtool no exist

tetra bugtool  
Error: unknown command "bugtool" for "tetra"
Run 'tetra --help' for usage.

### Relevant log output

```shell
time="2024-04-01T07:00:47Z" level=warning msg="failed to find cgroup id. Skipping container." container-id=6954470106531db33e78d8fd704522431f669518fa92a99bafd7fa6c807d3b94 error="found pod dir=/procRoot/1/root/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod30331b76_d205_4754_8dd8_34b33a95befc.slice but failed to find container for id=6954470106531db33e78d8fd704522431f669518fa92a99bafd7fa6c807d3b94" pod-id=30331b76-d205-4754-8dd8-34b33a95befc subsystem=policy-filter
```

```[tasklist]
### Tasks
- [ ] provide documentation about mount /proc on rke2
```

**Comment by kkourt** [comment]
Thanks for the report.

Are you experiencing any issues other than the warning itself?
For the bugtool report, please see https://tetragon.io/docs/troubleshooting/#automatic-log--state-collection.

**Comment by mtardy** [comment]
Also
```
tetra bugtool
Error: unknown command "bugtool" for "tetra"
Run 'tetra --help' for usage.
```
You are likely trying to run bugtool with a binary on macOS or Windows. The command is available in the Linux version of tetra.

**Comment by didlawowo** [comment]
> Thanks for the report!
> 
> Are you experiencing any issues other than the warning itself? For the bugtool report, please see https://tetragon.io/docs/troubleshooting/#automatic-log--state-collection.

i don't think so, but difficult to see with so many event

the problem about this warning it's make a lot a fake alert in the cluster

how can i fix it ?

**Comment by AlexLoMDB** [comment]
What happened here? Thanks
