### ISSUE TITLE
K8s Spec Mistmatch for uprobes

### ISSUE THREAD

**Issue by joshuajorel** [cilium/tetragon#2323]
### What happened?

1. Attempting to do the example for `uprobes` in the tetragon [documentation](https://tetragon.io/docs/concepts/tracing-policy/hooks/#uprobes:~:text=the%20bash%20binary%3A-,apiVersion%3A%20cilium.io/v1alpha1,%2D%20%22readline%22,-This%20example%20shows), I get the following error:

```
Error from server (BadRequest): error when creating "uprobe.yaml": TracingPolicy in version "v1alpha1" cannot be handled as a TracingPolicy: strict decoding error: unknown field "spec.uprobes[0].symbols"
``` 

Checking the CRD, the spec is written as `symbol` of type `string`. and not as `symbols` with a list of strings as type.

### Tetragon Version

CLI version: v1.0.1

### Kernel Version

Linux ubuntu-noble 6.8.0-11-generic #11-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 14 00:29:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

**Comment by lambdanis** [comment]
Hi @joshuajorel thanks for the report. This is a combination of two issues:
* There were some breaking changes in the TracingPolicy spec, which will be released in the next Tetragon release. This specific one was #1975.
* The documentation website is following the main branch, not a specific version at the moment. See also #1840.

So the uprobe example from the docs should work with the main branch of Tetragon (or the next release), but with v1.0.1 you need to change it to have `symbol: "readline"`. This situation is far from ideal, but hopefully it will improve soon.

**Comment by mtardy** [comment]
Thanks Anna for the detailed explanation on this!

I also agree that:
> This situation is far from ideal

And sorry for the breakage, but I don't think we can fix something here, next release should naturally "fix" this. Please reopen this issue if you disagree and think some actions could be taken.
