### ISSUE TITLE
docs: demo application `xwing` doesn't have `vi`

### ISSUE THREAD

**Issue by yukinakanaka** [cilium/tetragon#2334]
### What happened?

When I tried [Example in 'Filename access'](https://tetragon.io/docs/use-cases/filename-access/#examples), the following error occurred.

```
kubectl exec -it xwing -- /bin/bash
root@xwing:/# vi /etc/passwd
bash: vi: command not found
```

### Tetragon Version

CLI version: v1.1.0-pre.0-779-g429672e8b

### Kernel Version

Darwin P7DJ6J7VXF 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64

### Kubernetes Version

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

**Comment by mtardy** [comment]
Thanks for noticing that, taking a look at your PR.
