### ISSUE TITLE
tracing tests: Mkdir failed: mkdir /tmp2: file exists

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#238]
Using the new test option (`-disable-tetragon-logs`, https://github.com/cilium/tetragon/pull/237) I'm seeing:

```
--- PASS: TestKprobeObjectOpen (2.78s)  
=== RUN   TestKprobeObjectOpenMount     
    kprobe_test.go:583: Mkdir failed: mkdir /tmp2: file exists
    kprobe_test.go:584:                 
--- SKIP: TestKprobeObjectOpenMount (0.00s)
=== RUN   TestKprobeObjectMultiValueOpen
    jsonchecker.go:132: jsonTestCheck: opening: /tmp/tetragon.gotest.TestKprobeObjectMultiValueOpen.359677843.json
    filenames.go:60: deleting export file for TestKprobeObjectMultiValueOpen (/tmp/tetragon.gotest.TestKprobeObjectMultiValueOpen.359677843.json)
--- PASS: TestKprobeObjectMultiValueOpen (2.75s)
=== RUN   TestKprobeObjectMultiValueOpenMount
    kprobe_test.go:583: Mkdir failed: mkdir /tmp2: file exists
    kprobe_test.go:584:      
```

Which points to:
https://github.com/cilium/tetragon/blob/0c08c89c09b60043be5c0c6e8776619cb3d45e9a/pkg/sensors/tracing/kprobe_test.go#L578-L584

We should probably fix this since the test is skipped. I think the best option would be to create a temp directory (https://pkg.go.dev/os#MkdirTemp) for each test and remove it afterwards.

**Comment by jrfastab** [comment]
fixed here. https://github.com/cilium/tetragon/pull/255/commits/4351d2c688169e7ed3f2d631ca1b02ed8f5d0077
