### ISSUE TITLE
 Tetragon Go Test failing on actuated-arm64-4cpu-8gb: github.com/cilium/tetragon/pkg/sensors/tracing: TestTraceKernelModule

### ISSUE THREAD

**Issue by michi-covalent** [cilium/tetragon#2434]
github: https://github.com/cilium/tetragon/actions/workflows/gotests.yml?query=event%3Apush
slack: https://cilium.slack.com/archives/C03EV7KJPJ9/p1715729652070269

**Comment by kkourt** [comment]
@tixxdz you already seem to be working on this (https://github.com/cilium/tetragon/pull/2433) so I'm assigning to you.
