### ISSUE TITLE
config: move all cli flags to options.Config

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#245]
Similar to what was done [here](https://github.com/cilium/tetragon/pull/242), it would be nice to have all cli flags be backed by values in options.Config.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by haanhvu** [comment]
@willfindlay When you mentioned cli flags, did you mean this? https://github.com/cilium/tetragon/blob/main/cmd/tetragon/flags.go

I read the file and it seems like all option.Config fields have been backed there?

**Comment by Lan-ce-lot** [comment]
> I'll work on this

Are you still doing the work? I can help.
