### ISSUE TITLE
update docs to use NotifyEnforcer

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#2517]
https://github.com/cilium/tetragon/blob/main/docs/content/en/docs/concepts/tracing-policy/selectors.md#notify-killer-action

see: https://github.com/cilium/tetragon/pull/2117

**Comment by mtardy** [comment]
It's not completed yet, there are still some references in `docs` parts: see https://github.com/cilium/tetragon/pull/2518#pullrequestreview-2104007948.
