### ISSUE TITLE
Replace deprecated `grpc.DialContext`

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#2675]
### Context

[gRPC  Go]( https://github.com/grpc/grpc-go) deprecated `DialContext` with version `v1.63.0`.  We consistently use `DialContext` with `grpc.WithBlock()`. So switching to the recommended `NewClient` would change the behavior.

We need to figure out if we should change the behavior or somehow keep the current behavior while using `NewClient`.

### Acceptance Criteria

* The deprecated `DialContext` calls are replaced
* Related deprecated DialOptions are removed

### Related Links
* Upstream points out our current approach is an anti-pattern: https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc

**Comment by inliquid** [comment]
Also noticed this "deprecated" thing. The reason outlined is belonging to some "anti-pattern" list with no alternative solution. This sounds not very convincing:
> The reason these options can be a problem is that connections with a ClientConn are dynamic -- they may come and go over time. If your client successfully connects

I would say that __*I am pretty aware*__ of that, and in most of my cases this is __*absolutely fine*__. And there are lots of such cases out there. It would be pretty fine to just add these concerns to docs. I think we will continue using `grpc.WithBlock` unless it's gone forever, or someone else moved it from anti-pattern list. 

PS: Calling something anti-pattern is anti-pattern
