### ISSUE TITLE
tetragon helm-chart should install CRDs normally

### ISSUE THREAD

**Issue by cwrau** [cilium/tetragon#2716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

As a kubernetes administrator, I want to deploy tetragon declaratively, meaning no manual `apply`s, no operators creating CRDs, just [plain helm](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)

### Describe the feature you would like

If, for some reason, this is not doable, then it could be possible to put the [CRDs in a subchart](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts), which should allow the user to disable the normal CRDs.

### Describe your proposed solution

The tetragon helm-chart needs only to include the CRDs in the `crds` folder instead of `crds-yaml`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lambdanis** [comment]
Tetragon CRDs can be installed by Helm. You need to set the value:
```yaml
crds:
  installMethod: helm
```

The decision to not use the "official" Helm way to install CRDs by simply putting them in the crds directory was made to support CRD upgrades.

I'll close this issue, but if you have any issues with installing Tetragon CRDs then please comment.

**Comment by cwrau** [comment]
> Tetragon CRDs can be installed by Helm. You need to set the value:
> 
> ```yaml
> crds:
>   installMethod: helm
> ```

That is not the correct way, and not just semantically, as this blocks me from using this chart as a dependency

> The decision to not use the "official" Helm way to install CRDs by simply putting them in the crds directory was made to support CRD upgrades.

I _kinda_ get this, for people manually installing and maintaining their charts, but having them in the `crds` folder *and* in the template folder doesn't hurt anyone and makes it possible for gitops users to correctly install and maintain this chart (in conjunction with setting `crds.installMethod=crds` (which doesn't do anything))

**Comment by lambdanis** [comment]
@cwrau I don't fully understand, why setting the value doesn't work for you?

One problem with adding `crds` directory in addition to other CRDs install methods is that then Helm uses it by default. This can be confusing for existing users who expect CRDs to get automatically updated.

**Comment by cwrau** [comment]
> @cwrau I don't fully understand, why setting the value (via the deployment mechanism you're using) doesn't work for you?

Because this blocks me from using this as a dependency, as the CRDs are not installed first.

> One problem with adding `crds` directory in addition to other CRDs install methods is that then Helm uses it by default. This can be confusing for existing users who expect CRDs to get automatically updated.

But if the flag `crds.installMethod` is set to `operator` the operator will update them, no? Even if they are created first by helm

**Comment by lambdanis** [comment]
> Because this blocks me from using this as a dependency, as the CRDs are not installed first.

Ok, got it. If you need CRDs installed before resources from your chart, then they can't be just included in a subchart. You can still install Tetragon as a subchart, but CRDs have to be installed before (you can disable everything else in the chart to do so).

> But if the flag crds.installMethod is set to operator the operator will update them, no? Even if they are created first by helm

Good question, I'm not sure actually (CRDs installed with Helm won't have version label used by the operator). But an option to install CRDs via Helm was introduced for people who don't want to install operator at all, so this doesn't solve such case unfortunately.
