### ISSUE TITLE
[kind-setup] ERROR: image: "\"cilium/tetragon:latest\"" not present locally

### ISSUE THREAD

**Issue by ScriptSathi** [cilium/tetragon#2731]
### What happened?

When running `make kind-setup`, the script `./contrib/kind/install-tetragon.sh` is run, but the images could not be loaded correctly into kind. This makes the pods to run in error.

```
NAME                                 READY   STATUS             RESTARTS   AGE
tetragon-bs6rq                       1/2     ImagePullBackOff   0          14m
tetragon-operator-86dbcc5f8c-fdx74   0/1     ImagePullBackOff   0          14m
```

When taking the look at the pods, i get this

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m23s                   default-scheduler  Successfully assigned tetragon/tetragon-operator-86dbcc5f8c-rwvtj to tetragon-dev-control-plane
  Normal   Pulling    6m44s (x4 over 8m22s)   kubelet            Pulling image "cilium/tetragon-operator:latest"
  Warning  Failed     6m44s (x4 over 8m18s)   kubelet            Failed to pull image "cilium/tetragon-operator:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/cilium/tetragon-operator:latest": failed to resolve reference "docker.io/cilium/tetragon-operator:latest": docker.io/cilium/tetragon-operator:latest: not found
  Warning  Failed     6m44s (x4 over 8m18s)   kubelet            Error: ErrImagePull
  Warning  Failed     6m29s (x6 over 8m17s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m21s (x19 over 8m17s)  kubelet            Back-off pulling image "cilium/tetragon-operator:latest"
```

This means Kubernetes could not find "cilium/tetragon-operator:latest" remotely and locally.

### Tetragon Version

not concerned

### Kernel Version

not concerned

### Kubernetes Version

v1.25 (latest from tetragon setup)

**Comment by mtardy** [comment]
It's funny I bumped into this issue exactly right now as well. There was something off with the kind load docker-image cmd, as soon as I did by hand it worked.

**Comment by ScriptSathi** [comment]
I'm writting the PR for this issue. Just wait few minutes

**Comment by lambdanis** [comment]
@ScriptSathi @mtardy What version of yq are you using? I didn't have this issue locally, but different yqs behave differently even for simple operations, it's so tricky to use it.
