### ISSUE TITLE
docs: Network Monitoring SERVICECIDR command for KinD doesn't work for named clusters

### ISSUE THREAD

**Issue by tiswanso** [cilium/tetragon#3182]
In the section [Monitoring Kubernetes Network Access](https://tetragon.io/docs/getting-started/network/#monitoring-kubernetes-network-access), the command in the KinD tab for the SERVICECIDR env var assumes the KinD cluster is created without a name.  

To avoid the naming issue it should match on the kube-apiserver component label instead like:

```
export SERVICECIDR=$(kubectl describe pod -n kube-system -l component=kube-apiserver | awk -F= '/--service-cluster-ip-range/ {print $2; }')
```

**Comment by mtardy** [comment]
Hello! Good idea, would you like to do a documentation PR to fix that? :)
