### ISSUE TITLE
CI failure: TestFastK8s

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#3213]
Failure:
```
=== RUN   TestFastK8s
    watcher_test.go:35: time="2024-12-09T09:57:55Z" level=info msg="Initialized informer cache" count=0 informer=pod
        
    watcher_test.go:97: adding pod
    watcher_test.go:105: deleting pod
    watcher_test.go:110: 
                Error Trace:    /home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/watcher/watcher_test.go:110
                Error:          Should be true
                Test:           TestFastK8s
                Messages:       deleted pod should be found
--- FAIL: TestFastK8s (0.12s)
FAIL
```

https://github.com/cilium/tetragon/pull/3198

**Comment by mtardy** [comment]
we have https://github.com/cilium/tetragon/issues/2972

**Comment by kkourt** [comment]
> we have [#2972](https://github.com/cilium/tetragon/issues/2972)

Hmm... strange I remember having seen it before, but the test does not return anything.

![Image](https://github.com/user-attachments/assets/1a0815e2-4464-4496-8170-cc9e6ff93215)

Oh well...

**Comment by mtardy** [comment]
ah indeed you need to type the full word to see it, nice github search lol

<img width="593" alt="Image" src="https://github.com/user-attachments/assets/827c45d5-7617-451b-b8a6-36ceac9a6266" />

**Comment by mtardy** [comment]
Didn't we disabled that test https://github.com/cilium/tetragon/actions/runs/13568101819/job/37926370844?pr=3434#step:6:2061 ? It's still running in vmtest

**Comment by kkourt** [comment]
We [did](https://github.com/cilium/tetragon/pull/3356), but we (I) never backported the changes.

**Comment by mtardy** [comment]
> We [did](https://github.com/cilium/tetragon/pull/3356), but we (I) never backported the changes.

ah yes nevermind indeed, it's on a stable branch :) thank you
