### ISSUE TITLE
tetra  debug progs bug

### ISSUE THREAD

**Issue by panzhenyu12** [cilium/tetragon#3234]
### What happened?

1.kernel version 5.15.0, tetragon version 1.30
2.tp config
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-tamper-delete"
spec:
  kprobes:
  - call: "security_path_unlink"
    syscall: false
    return: true
    args:
    - index: 0
      type: "path" 
    - index: 1
      type: "nop" 
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/home/appuser/test"          
      matchActions:
      - action: Override
        argError: -1
3. run tetra debug progs, show msg info for /sys/fs/bpf/tetragon/file-tamper-delete/generic_kprobe/security_path_unlink/link_override: argument list too long

### Tetragon Version

v1.3.0

### Kernel Version

Linux 5.15.0-71-generic

### Bugtool

time="2024-12-17T16:32:00+08:00" level=info msg="saving init info"
time="2024-12-17T16:32:00+08:00" level=info msg="retrieving lib directory" libDir=/usr/local/lib/tetragon/bpf/
time="2024-12-17T16:32:00+08:00" level=warning msg="not an object file, ignoring" path=/usr/local/lib/tetragon/bpf/
time="2024-12-17T16:32:03+08:00" level=warning msg="no btf filename in tetragon config, attempting to fall back to /sys/kernel/btf/vmlinux"
time="2024-12-17T16:32:04+08:00" level=info msg="btf file added" btfFname=/sys/kernel/btf/vmlinux
time="2024-12-17T16:32:04+08:00" level=info msg="tetragon log file added" exportFname=/var/log/tetragon/tetragon.log
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd=/usr/bin/dmesg dstFname=dmesg.out ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev lo ingress" dstFname=tc-info.lo.ingress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev lo egress" dstFname=tc-info.lo.egress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev eth0 ingress" dstFname=tc-info.eth0.ingress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev eth0 egress" dstFname=tc-info.eth0.egress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev docker0 ingress" dstFname=tc-info.docker0.ingress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/sbin/tc filter show dev docker0 egress" dstFname=tc-info.docker0.egress ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/local/lib/tetragon/bpftool map show -j" dstFname=bpftool-maps.json ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/local/lib/tetragon/bpftool prog show -j" dstFname=bpftool-progs.json ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/local/lib/tetragon/bpftool cgroup tree -j" dstFname=bpftool-cgroups.json ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="Skipping gops dump info as daemon is running without gops, use --gops-address to enable gops"
time="2024-12-17T16:32:04+08:00" level=warning msg="failed to open policyfilter map" error="no such file or directory"
time="2024-12-17T16:32:04+08:00" level=info msg="dumped tracing policies in tracing-policies.json"
time="2024-12-17T16:32:04+08:00" level=info msg="executed command" cmd="/usr/bin/pmap -x 2985124" dstFname=pmap.out ret=0
time="2024-12-17T16:32:04+08:00" level=info msg="cgroup file added" file=memory.usage_in_bytes
time="2024-12-17T16:32:04+08:00" level=info msg="retrying to read cgroup file from a different legacy path" cgroupPath=/sys/fs/cgroup/memory
time="2024-12-17T16:32:04+08:00" level=info msg="cgroup file added" file=memory.usage_in_bytes
time="2024-12-17T16:32:04+08:00" level=info msg="cgroup file added" file=memory.kmem.usage_in_bytes
time="2024-12-17T16:32:04+08:00" level=info msg="cgroup file added" file=memory.stat
time="2024-12-17T16:32:05+08:00" level=warning msg="failed to run BPF maps checks" error="failed to retrieve maps used by pinned progs: failed retrieving map IDs: failed walking the path \"/sys/fs/bpf/tetragon\": failed to load pinned object \"/sys/fs/bpf/tetragon/file-tamper-delete/generic_kprobe/security_path_unlink/link_override\": info for /sys/fs/bpf/tetragon/file-tamper-delete/generic_kprobe/security_path_unlink/link_override: argument list too long"
time="2024-12-17T16:32:05+08:00" level=info msg="executed command" cmd="/usr/bin/cat /sys/kernel/tracing/trace" dstFname=trace ret=0

### Relevant log output

```shell

```

**Comment by panzhenyu12** [comment]
[tetragon-bugtool.tar.gz](https://github.com/user-attachments/files/18162633/tetragon-bugtool.tar.gz)

**Comment by mtardy** [comment]
Hey, thanks for the bug report!

cc @olsajiri
