### ISSUE TITLE
Code style checking: checkpatch and clang-format clash on BPF files

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#344]
On bpf source files our checkpatch and clang-format tool clash on some trivial style violations:

- clang-format will format the open brace on type declaration on next lines, example:
```
  enum msg_cgroup_ops {
  ...
  
  to

  enum msg_cgroup_ops
  {
```

- While checkpatch will report:
```
  Error: ERROR:OPEN_BRACE: open brace '{' following enum go on the same line
  #41: FILE: bpf/lib/msg_types.h:36:
  +enum msg_cgroup_ops
  +{
```

I tend to prefer checkpatch style, but clang people may know better... so no preference , since we want the clang-format part of the build and it auto fixes files, maybe we relax checkpatch?

**Comment by kkourt** [comment]
Seems related to b31cb1c262b071b777ad406aacf060876039b087

**Comment by kkourt** [comment]
This seems that is already addressed by https://github.com/cilium/tetragon/commit/b31cb1c262b071b777ad406aacf060876039b087, closing.
