### ISSUE TITLE
[Question] TracingPolicy for specific pods

### ISSUE THREAD

**Issue by andylibrian** [cilium/tetragon#365]
Hi,

Is it currently possible to have a TracingPolicy for specific pods? I would like to apply `action: Sigkill`, almost like https://github.com/cilium/tetragon/blob/main/crds/examples/names.yaml but on some specific pods (by K8s namespace, or by pod name).

I looked at all `crds/examples/` but couldn't find any configuration for specific pods.

**Comment by andylibrian** [comment]
Thanks for letting me know, @kkourt. That's a good news. Is the roadmap public or private? I'm interested to follow.

**Comment by jrfastab** [comment]
We haven't got to pushing a public roadmap yet but will do that shortly.

But, this is supported now! So feature implemented and closing.
