### ISSUE TITLE
Issues Testing open_kill.yaml example.

### ISSUE THREAD

**Issue by Scrier** [cilium/tetragon#440]
### Initial Issue

I ran through your readme to an dincluding the _priviliged execution_. After this I try to apply the _open_kill.yaml_ without result. `https://raw.githubusercontent.com/cilium/tetragon/main/crds/examples/open_kill.yaml`. Writing to /etc/passwd in the xwing pod is  still viable.

Restarting the tetragon service with `kubectl rollout restart -n kube-system ds/tetragon` still left me with write options in the folder.

### Slack debugging

I posted the issue on slack and tested the following things:

#### Restart the service and tetragon and just applying the open_kill.yaml

```
  389  kubectl delete -f https://raw.githubusercontent.com/cilium/cilium/v1.11/examples/minikube/http-sw-app.yaml
  390  helm uninstall tetragon -n kube-systemhelm install tetragon cilium/tetragon -n kube-system
  391  helm install tetragon cilium/tetragon -n kube-system
  392  kubectl rollout status -n kube-system ds/tetragon -w
  393  kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.11/examples/minikube/http-sw-app.yaml
  394  kubectl apply -f https://raw.githubusercontent.com/cilium/tetragon/main/crds/examples/open_kill.yaml
``` 

This still gave no effect changing the password in the xwing container.

#### Remove other policies and restart the tetragon service.

```
  421  kubectl delete -f https://raw.githubusercontent.com/cilium/cilium/v1.11/examples/minikube/http-sw-app.yaml
  422  helm uninstall tetragon -n kube-system
  427  k delete tracingpolicies syswritefollowfdpsswd
  428  k get tracingpolicies
  430  helm install tetragon cilium/tetragon -n kube-system
  431  kubectl rollout status -n kube-system ds/tetragon -w
  432  kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.11/examples/minikube/http-sw-app.yaml
  433  k get all
  434  kubectl apply -f https://raw.githubusercontent.com/cilium/tetragon/main/crds/examples/open_kill.yaml
  436  k get tracingpolicy
  437  kubectl rollout restart -n kube-system ds/tetragon
  438  kubectl logs -n kube-system ds/tetragon -c tetragon
```

After restart it still does not affect output. The `syswritefollowfdpsswd` is the only active policy at this time.

For additional info you can check the slack entry by me (Andreas Joelsson) for the date 2022-09-23

**Comment by jrfastab** [comment]
This should be resolved by now.
