### ISSUE TITLE
avoid having to run the 'go' compiler with sudo in 'make test'

### ISSUE THREAD

**Issue by dmitris** [cilium/tetragon#46]
Currently you have to run 'make test' with sudo (understandably since you need to load BPF programs etc.) which also runs the `go` compiler with elevated priviledges - which makes some hard-core Paranoids cringe with fear and lose their sleep 😄.  The compiler - even as wonderful and well-cared-for as Go - is a big and complex piece of software and can at some times have some bugs, running a compiler as sudo is against the good security practices and also is not necessary.  We should build the test binaries with `go test -c` in a make step that doesn't require 'sudo', and then only run those test binaries with sudo.

In the output of `make` I already see some test binaries being made:
```
go build -gcflags="" -ldflags="-X 'github.com/cilium/tetragon/pkg/version.Version=v0.8.0-24-g61731ca'" -mod=vendor -o tetragon-alignchecker ./tools/alignchecker/
mkdir -p go-tests
go test -gcflags="" -c ./pkg/bugtool         -o go-tests/bugtool.test
go test -gcflags="" -c ./pkg/filters         -o go-tests/filters.test
go test -gcflags="" -c ./pkg/grpc            -o go-tests/grpc.test
go test -gcflags="" -c ./pkg/metrics         -o go-tests/metrics.test
go test -gcflags="" -c ./pkg/stacktracetree  -o go-tests/stacktracetree.test
go test -gcflags="" -c ./pkg/vtuplefilter    -o go-tests/vtuplefilter.test
go test -gcflags="" -c ./pkg/tracepoint      -o go-tests/tracepoint.test
go test -gcflags="" -c ./pkg/config          -o go-tests/config.test
go test -gcflags="" -c ./pkg/idtable         -o go-tests/idtable.test
go test -gcflags="" -c ./pkg/bpf             -o go-tests/bpf.test
go test -gcflags="" -c ./pkg/btf             -o go-tests/btf.test
make -C contrib/sigkill-tester
```

Are these all or only some? We should build all test binaries like this in a step other than `make test` (that one would run with sudo), maybe just in `make` itself or one of its dependencies.

**Comment by willfindlay** [comment]
> Are these all or only some? We should build all test binaries like this in a step other than make test (that one would run with sudo), maybe just in make itself or one of its dependencies.

Right, it's non-exhaustive at the moment. I think the "right" way to do this would probably be with a glob in the Makefile that compiles all tests (rather than hard-coding each one which, as you've pointed out is very error-prone as new tests are added). Then we would have another target as you suggest that would run each test (also using a glob).

A PR would be much appreciated!

**Comment by kkourt** [comment]
Above ☝🏼 exists now (test-compile target), so closing this.
