### ISSUE TITLE
bpf: review and fix 0xeff masks

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#462]
https://github.com/cilium/tetragon/commit/867c6f09be293fce279e09e28e9ed6392f935c85 fixes a 0xeff mask to 0xfff. There are other instances of such masks on the code, which might lead to similar bugs. Changing all of them, however, leads to verification issues so they need to be reviewed on a case-by-case basis.

see: https://github.com/cilium/tetragon/pull/458#discussion_r985674185

**Comment by tpapagian** [comment]
Now sure that this is related but we still have some `0xeff` masks:
```
~/tetragon/bpf$ grep 3ff. -rnI
process/types/basic.h:177:	asm volatile("%[off] &= 0x3fff;\n" ::[off] "+r"(off)
process/types/basic.h:1490:		size = argm & 0x03ff;
process/data_event.h:24:	asm volatile("%[bytes] &= 0x3fff;\n"
process/pfilter.h:131:		asm volatile("%[o] &= 0x3ff;\n" ::[o] "+r"(o)
process/pfilter.h:150:		asm volatile("%[o] &= 0x3ff;\n" ::[o] "+r"(o)
process/bpf_process_event.h:386:	asm volatile("%[offset] &= 0x3ff;\n" ::[offset] "+r"(offset)
```
