### ISSUE TITLE
Network Event Rollup

### ISSUE THREAD

**Issue by levigross** [cilium/tetragon#467]
Hello,

I would love to help with rolling up network events e.g `tcp_sendmsg` and `udp_sendmsg`. Is this on the roadmap? If so, how can I help?

**Comment by kkourt** [comment]
To my knowledge, this is not in the roadmap.

Based on the definition below:
> int [tcp_sendmsg](https://elixir.bootlin.com/linux/latest/C/ident/tcp_sendmsg)(struct [sock](https://elixir.bootlin.com/linux/latest/C/ident/sock) *sk, struct [msghdr](https://elixir.bootlin.com/linux/latest/C/ident/msghdr) *msg, [size_t](https://elixir.bootlin.com/linux/latest/C/ident/size_t) size);

It seems that one missing piece is adding support for `struct msghdr` arguments.

If this is something that you (or someone else) is interested in working on, we 'd be happy to help. We do not, currently, have a lot of development documentation, but this might be a good opportunity to fix that.

**Comment by levigross** [comment]
There is another issue :) 

`tcp_sendmsg` is called so many times (and very fast) that you lose calls within the circular buffer. I think it would need to be rolled up within ebpf

**Comment by anjmao** [comment]
Hi @levigross 

In test cluster I generate 5k/s tcp_sendmsg messages. Was able to reduce dropped ring buffer messages by increasing `    rb-size`. Default is only 65k bytes which is way to small for networking events tracing.
<img width="1851" alt="stats" src="https://user-images.githubusercontent.com/3028012/204319678-7747e728-44ef-4f85-9c92-bd24699986fd.png">


Another issue is that userspace is not able to keep up and consume events from Go channels. Even increasing events channel size doesn't help.
<img width="2164" alt="flame" src="https://user-images.githubusercontent.com/3028012/204320082-ecc5e7d7-3efa-4ee6-8ef3-58576627645a.png">

There are few issues:
* Log exported can't keep up.
* Most of the CPU is spent marshaling json + bunch reflect. This also creates lots of garbage on heap. Standard library json can be replaced by something like json-iter(also used in k8s).

**Comment by levigross** [comment]
@anjmao Thank you for this brilliant outline of the issue! IMHO the network events needs to rolled up *within BPF* and need to be emitted as a singular event

**Comment by anjmao** [comment]
Currently I'm using https://vector.dev/docs/reference/configuration/transforms/reduce/ to reduce events and sum bytes field in userspace.

```json
{
  "bytes": 384,
  "daddr": "10.128.0.67",
  "dport": [
    9990,
    2112
  ],
  "node_name": "node-e6149004",
  "pid": 45735,
  "pod_name": "metrics-0",
  "pod_namespace": "grafana",
  "saddr": "10.104.0.5",
  "sport": [
    52938,
    27350
  ]
}
```

Also, it's important to adjust tetragon resources and add cpu requests. In my case I got dropped exported events due to lack of cpu.

To implement such reduction on kernel something like ebpf timers https://lwn.net/Articles/862136/ could be really useful (not sure about the support yet)
