### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#487]
This would allow to run tetragon on ARM machines, including VMs running on M1 machines.

See:
 * https://github.com/cilium/tetragon/issues/190
 * https://github.com/cilium/tetragon/pull/451
 * https://github.com/cilium/tetragon/pull/472
 
Let's recap the recent updates:
- https://github.com/cilium/tetragon/pull/734
- https://github.com/cilium/tetragon/pull/743
- https://github.com/cilium/tetragon/pull/752
- https://github.com/cilium/tetragon/pull/734
- https://github.com/cilium/tetragon/pull/816
- https://github.com/cilium/tetragon/pull/856
- https://github.com/cilium/tetragon/pull/880
- https://github.com/cilium/tetragon/pull/886
- https://github.com/cilium/tetragon/pull/884
- https://github.com/cilium/tetragon/pull/899
- https://github.com/cilium/tetragon/pull/900

We still have a minor few issues:
- https://github.com/cilium/tetragon/issues/786 _(this might not be really an issue)_
- https://github.com/cilium/tetragon/issues/776 _(this is very limited, only one test remaining)_
- https://github.com/cilium/tetragon/issues/955

We will continue the work on those issues but we can close this umbrella "arm64 support" issue since Tetragon now runs on arm64.

**Comment by mtardy** [comment]
For the update we merged the following:
- https://github.com/cilium/tetragon/pull/743
- https://github.com/cilium/tetragon/pull/752
- https://github.com/cilium/tetragon/pull/734

So now Tetragon should compile and run transparently (like it does on amd64):
```shell
make tetragon tetragon-bpf
sudo ./tetragon --bpf-lib bpf/objs
```

However, we identified a few limitations:
- https://github.com/cilium/tetragon/issues/786
- https://github.com/cilium/tetragon/issues/776
- The CI is still `amd64`-centric
- While you can build it yourself, we still don't build and distribute Tetragon container images for arm64.

**Comment by mtardy** [comment]
To let people play with Tetragon on arm64, I tried to address the last point:
> While you can build it yourself, we still don't build and distribute Tetragon container images for arm64.

- https://github.com/cilium/tetragon/pull/816

**Comment by errordeveloper** [comment]
Hey folks, are there multi-arch images could try already? Just very keep to play with Teragon on amd64+arm64 cluster :)

**Comment by errordeveloper** [comment]
@mtardy thanks a lot! it seems like `quay.io/cilium/tetragon-operator-ci:latest` wasn't built for arm64, I'm seeing this:
```
$ kubectl logs -n kube-system tetragon-bnzd7 -c  tetragon-operator 
exec /usr/bin/tetragon-operator: exec format error
$
```

**Comment by mtardy** [comment]
> @mtardy thanks a lot! it seems like `quay.io/cilium/tetragon-operator-ci:latest` wasn't built for arm64, I'm seeing this:
> 
> ```
> $ kubectl logs -n kube-system tetragon-bnzd7 -c  tetragon-operator 
> exec /usr/bin/tetragon-operator: exec format error
> $
> ```

For the record, I broke the `tetragon-operator` build on arm64 because of [a previous Makefile change](https://github.com/cilium/tetragon/commit/dfa2048d59deae918f8ab76ea3afed9c0e95b8a2#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R142). See the following for a fix: 
- https://github.com/cilium/tetragon/pull/880

**Comment by mtardy** [comment]
New arm64 PRs for documentation and examples:
- https://github.com/cilium/tetragon/pull/886
- https://github.com/cilium/tetragon/pull/884

**Comment by mtardy** [comment]
I just edited the first message with a recap of all the updates and why we can now close this issue, [see this](https://github.com/cilium/tetragon/issues/487#issue-1414761135).
