### ISSUE TITLE
cleanup: merge Config.BpfDir and Config.MapDir

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#527]
Configuration defines a BpfDir and a MapDir:
https://github.com/cilium/tetragon/blob/411aa54de1697a0ee84f67453a380543e89c801a/pkg/option/config.go#L34-L35

This is the base directory for the pinned bpf programs and maps.
In most cases, however, they are the same.
E.g., https://github.com/cilium/tetragon/blob/411aa54de1697a0ee84f67453a380543e89c801a/cmd/tetragon/main.go#L179-L180

We can simplify the code and merge them into one.

**Comment by Lan-ce-lot** [comment]
Hi, I want to try to solve it.

**Comment by jrfastab** [comment]
@Lan-ce-lot feel free to tackle this if you want. I think it is a nice improvement.
