### ISSUE TITLE
Is it working with any cni?

### ISSUE THREAD

**Issue by Diliz** [cilium/tetragon#549]
Hello there!

Sorry to bother you with that, I currently am facing issues with dropped network policies with another cni, and I can't see this kind of network events with some other security tools.

Will I be able to see the realtime traffic as well as see dropped event from any cni (with bpf etc...) other than cillium?
Sounds like a stupid question, but didn't found if it was explicity stated that tetragon is only for cillium, or otherwise.

If it's not only for cillium or if features can't be used without cillium, can you give a link to the documentation (if it's already documented) specifying one of the two possibilities?

Anyway i'll try it without cillium to see if it's working with my cluster.

**Comment by kkourt** [comment]
Tetragon can work without Cilium.
Being able to seeing dropped traffic and dropped events with Tetragon is another question.
This can be currently done with Hubble, which does depend on Cillium. See: https://docs.cilium.io/en/stable/intro/.

**Comment by Diliz** [comment]
Thanks for the fast answer, out of topic then and sorry to ask it here then, is it possible to use hubble with cillium cni chaining only?

**Comment by kkourt** [comment]
> Thanks for the fast answer, out of topic then and sorry to ask it here then, is it possible to use hubble with cillium cni chaining only?

I would think so. However, as you said, this question is probably better asked in a cilium-specific forum. See: https://github.com/cilium/cilium/#community.
