### ISSUE TITLE
char_buf args probabilistically empty or useless

### ISSUE THREAD

**Issue by Y-dc** [cilium/tetragon#562]
I want to get char_buf args from tracepoint ```sys_enter_write``` or ```sys_enter_read``` , but probabilistically i got empty or useless value from the output events. 
i found that ```size``` of ```bpf_probe_read``` in ```__copy_char_buf```  used ```rd_bytes &= 0xfff```,  this is the source.
[source code](https://github.com/cilium/tetragon/blob/c338a633b4818dba9ba327188531da4a1f76c9f7/bpf/process/types/basic.h#L524).
<img width="620" alt="image" src="https://user-images.githubusercontent.com/39187264/204265666-b8edf37b-dbfc-4f01-8662-db357797b62d.png">

if the ```bytes > 0xfff```, Is it possible to take the value ```rd_bytes``` as ```0xfff```.

**Comment by kkourt** [comment]
I believe we are truncating the length to avoid overflowing the buffer. Is the issue that you want to buffers that are larger than 4K?

note that https://github.com/cilium/tetragon/pull/116 solved a similar issue.
