### ISSUE TITLE
repository for tetragon helm chart

### ISSUE THREAD

**Issue by NissesSenap** [cilium/tetragon#57]
Hi

Currently rather painful to be forced to download the github repo and run a local helm install.
I assume that you will start working on this when everything get's a bit more stable but always good to have an issue open.

In short please provide tetragon in a public repository, just like https://helm.cilium.io/.

**Comment by willfindlay** [comment]
Hi @NissesSenap, yes putting the helm chart into a public repo is in the works. The chart in this repository is just a temporary stopgap.

**Comment by willfindlay** [comment]
@michi-covalent can we close this after #66 or is there more work to do?

**Comment by michi-covalent** [comment]
yeah let's close it
