### ISSUE TITLE
tetragon: base execve sensor improvements 

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#570]
Improve our base execve sensor with default detection:
- [x] detect execve unlinked programs (cover all different cases): https://github.com/cilium/tetragon/pull/499
- [x] detect setuid/setgid and fscaps https://github.com/cilium/tetragon/pull/1296

**Comment by tixxdz** [comment]
Maybe:
- [ ] detect that an exec is being ptraced
- [x] detect user mod helper execution (Not worth it for now)

**Comment by kkourt** [comment]
Closing this since most of the work is done! :tada:
