### ISSUE TITLE
ci: use large GHA runner

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#608]
cilium/cilium has started using large GitHub Action Runners to run multi-kernel tests. Since they support nested KVM virtualization, they are much faster than the approach we are using here.

Currently, we are using aggressive job splitting to parallelize our existing workflow and work around this slowness. With a large GHA runner, we could eliminate or at least reduce the need to do this while speeding up CI jobs by about 2x.

**Comment by willfindlay** [comment]
The steps needed to do this would basically be:

1. Enable large GHA runners for this repo (cc @aanm)
2. Change ubuntu-20.04 runner to a large GHA runner
3. Reduce the group count to 1 in the gotests job to prevent hogging too many resources

**Comment by aanm** [comment]
@willfindlay this should be done now
