### ISSUE TITLE
Publish nightly releases

### ISSUE THREAD

**Issue by levigross** [cilium/tetragon#622]
Hello,

With the development of tetragon moving so fast, I would love it if you were able to publish a nightly container images (so that I can try out bug fixes without having to build the image locally). 

Thanks 😊

**Comment by kkourt** [comment]
Hi,

There are images build for every PR merged in the `main` branch: https://github.com/cilium/tetragon/actions/workflows/build-images-ci.yml?query=branch%3Amain. 

We don't have a `latest` tag, but you can access images using the commit hash.
For example, current `main` SHA is `00b98468466212ce5acfe8b992205056fb3fa304`. Corresponding images are:

* `quay.io/cilium/tetragon-ci:00b98468466212ce5acfe8b992205056fb3fa304`
* `quay.io/cilium/tetragon-operator-ci:00b98468466212ce5acfe8b992205056fb3fa304`

Note that the build action has a final step that displayes the digests. For the current latest one, see: https://github.com/cilium/tetragon/actions/runs/3942673957/jobs/6746701845#step:4:1.

**Comment by tixxdz** [comment]
hi @levigross actually we have instructions on how to run latest ci build / dev images here: https://github.com/cilium/tetragon/tree/main/docs/deployment/docker#unstable-development-versions

I guess we have to organize better our doc so this section is reachable.
