### ISSUE TITLE
test for retrieving exit code

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#634]
Add a test to check that tetragon returns the exit code of the process correctly. (see: https://github.com/cilium/tetragon/pull/630)

**Comment by zhy76** [comment]
I'm interested in this, but I'm new here, could you give me more suggestion?

**Comment by kkourt** [comment]
Programs have an exit code that indicate whether there is an error or not. In a shell such as bash, the error code is accessible via the `$?` environment variable.

E.g.,


```shell-session
$ bash -c 'exit 42'
$ echo $?
42
```

The purpose here is to write a test that executes such a program and checks that the status value in Tetragon exit event (see: https://github.com/cilium/tetragon/tree/main/api/v1#tetragon-ProcessExit) is the actual exit value.

Some example tests can be found in: https://github.com/cilium/tetragon/blob/main/pkg/sensors/exec/exit_test.go
