### ISSUE TITLE
doc: document Tetragon configuration options

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#640]
Document Tetragon configuration options and add some suggestions that relate to how to run it in bare metal.

Example see: #635

**Comment by mtardy** [comment]
So now we have:
- Tetragon configuration ref doc page: https://tetragon.io/docs/reference/daemon-configuration/
- Tetragon package deployment: https://tetragon.io/docs/installation/package/

I'll close this for now, please reopen Djalal if you think this is still needed, or open another one for improvement on that.
