### ISSUE TITLE
Add metrics for lru cache in pkg/observer/data.go

### ISSUE THREAD

**Issue by olsajiri** [cilium/tetragon#679]
would be good to add metrics for lru cache in `pkg/observer/data.go`,
like we do in `pkg/process/cache.go`

so we can eventually watch and suggest better value for the cache

**Comment by kkourt** [comment]
@rajaSahil I'm not aware of anyone working on it, so yes :)

**Comment by kkourt** [comment]
> @kkourt Thank you! Can you please assign it to me?

Sure thing! Let me know if you need any help.

**Comment by Neilblaze** [comment]
@rajaSahil are you still on it? If not we can collaborate. @kkourt If possible can you assign both of us? 😄

**Comment by Neilblaze** [comment]
Update: As a newcomer, I've been trying my level best to get familiar with the codebase. Here's my [approach](https://github.com/Neilblaze/tetragon/blob/tetragon-Add-metrics-for-lru-cache-in-pkg/observer/data.go/pkg/observer/data.go) & the following changes can be observed [here](https://github.com/Neilblaze/tetragon/commit/62269a8beaedbdda5698aa9798a8bbf2adbc4200). Lemme know if I need to update anything.

cc: @kkourt

**Comment by Neilblaze** [comment]
@YTGhost But yeah, no worries! you can go ahead & raise a PR if you want.

**Comment by mtardy** [comment]
> Update: As a newcomer, I've been trying my level best to get familiar with the codebase. Here's my [approach](https://github.com/Neilblaze/tetragon/blob/tetragon-Add-metrics-for-lru-cache-in-pkg/observer/data.go/pkg/observer/data.go) & the following changes can be observed [here](https://github.com/Neilblaze/tetragon/commit/62269a8beaedbdda5698aa9798a8bbf2adbc4200). Lemme know if I need to update anything.
> 
> cc: @kkourt

your links are private, please create a PR or a draft PR if you want someone to review your changes.

**Comment by Neilblaze** [comment]
@mtardy Oh no! I just realized that I mistakenly force-pushed all the master content into the working branch, thus overriding the entire data. 😓

I'll have to check if I can recover it, but in the meantime, YTGhost can work on it.

**Comment by mtardy** [comment]
Ok I'll unassign this for now. If anyone wants to take this.

**Comment by AshishNaware** [comment]
question - what kind of metrics are expected to be added here? Is it about adding error metrics after cache eviction?

**Comment by mtardy** [comment]
> question - what kind of metrics are expected to be added here? Is it about adding error metrics after cache eviction?

hey @lambdanis would you have more context on this since you recently touched the process event cache metrics? :)

**Comment by lambdanis** [comment]
So at the moment Tetragon exposes four metrics: size, capacity, evictions and misses for [process cache](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/process/cache.go#L17). Metrics are defined [here](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/process/metrics.go#L20-L40). Ideally we would have analogous metrics for the [dataMap](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/observer/data.go#L23) thing.

**Comment by AshishNaware** [comment]
> So at the moment Tetragon exposes four metrics: size, capacity, evictions and misses for [process cache](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/process/cache.go#L17). Metrics are defined [here](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/process/metrics.go#L20-L40). Ideally we would have analogous metrics for the [dataMap](https://github.com/cilium/tetragon/blob/4360b2826bd64604dfb7b28d0d5f97965050f54a/pkg/observer/data.go#L23) thing.

Thanks for the clarification. Is anyone already working on this issue? If not, i can take this.

**Comment by lambdanis** [comment]
> Thanks for the clarification. Is anyone already working on this issue? If not, i can take this.

I don't think so, feel free to open a PR @AshishNaware

**Comment by AshishNaware** [comment]
@lambdanis - what triggers the data events in tetragon observer? Is there any specific tracing policy I need to add to monitor those events? I am trying to test my changes by manually triggering these events and monitor them in prometheus.

**Comment by lambdanis** [comment]
> what triggers the data events in tetragon observer? Is there any specific tracing policy I need to add to monitor those events?

@AshishNaware The data events are produced on process execution. No policy needed, this is included in the base Tetragon installation.
