### ISSUE TITLE
Privileged execution use case: use nginx instead of test-pod image

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#705]
In the documentation on the privileged execution use case:

https://github.com/cilium/tetragon/blob/f4d6ac470658375109bcb37cfbe679b5432cdf6d/README.md?plain=1#L594-L609

We could use a more realistic example, using an nginx image instead of the test-pod made-up image.

> Let's do it. I'd just use a simple nginx pod spec for this, e.g:
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: privileged-the-pod
> spec:
>   hostPID: true
>   hostNetwork: true
>   containers:
>   - name: privileged-the-pod
>     image: nginx:latest
>     ports:
>     - containerPort: 80
>     securityContext:
>       privileged: true
> ```
> 
_Originally posted by @sharlns in https://github.com/cilium/tetragon/pull/673#discussion_r1112219567_

**Comment by janvi01** [comment]
Hey @mtardy I would like to work on this.
