### ISSUE TITLE
refactor: merge go modules

### ISSUE THREAD

**Issue by ernado** [cilium/tetragon#712]
Currently, tetragon is split into 3 modules:
- `github.com/cilium/tetragon/pkg/k8s`
- `github.com/cilium/tetragon/api`
- `github.com/cilium/tetragon`

Also, there is recursive dependency beteen `github.com/cilium/tetragon` and `github.com/cilium/tetragon/api`, and none of them are go-gettable because of it.

Moreover, following is invalid:
```
	github.com/cilium/tetragon/api v0.0.0-00010101000000-000000000000
	github.com/cilium/tetragon/pkg/k8s v0.0.0-00010101000000-000000000000
```
Because `replace`-es are working only locally and ignored during go-get, and `v0.0.0-00010101000000-000000000000` is not a valid revision.

I propose to merge all three of them, or at least root and `/api`, because it seems like it is impossible to resolve recursive dependencies.

### Why they should be go-gettable
I'm using gRPC client to connect to tetragon and want to use `github.com/cilium/tetragon/api` for it.

**Comment by ernado** [comment]
:thinking: that's strange, it worked for me too now.

I'll close this issue for now, probably I messed up with my local setup in some way, thank you.

**Comment by smff** [comment]
same thing(issue) right now(

<img width="507" height="431" alt="Image" src="https://github.com/user-attachments/assets/144290d8-04c6-41f7-9170-1939a606ef07" />

<img width="539" height="317" alt="Image" src="https://github.com/user-attachments/assets/a153a2be-3c5b-49c8-9ccc-c8577610756d" />

<img width="960" height="347" alt="Image" src="https://github.com/user-attachments/assets/3f4416a8-ea6c-42d1-8ce6-71f52d154ccc" />

**Comment by kemingy** [comment]
I also ran into this weird error when I was trying to include my project (with a tetragon gRPC client) in a Go workspace. Suddenly, everything stopped working. Removing all the Go workspace related files fixed it.

This can be reproduced by the example provided above: https://github.com/cilium/tetragon/issues/712#issuecomment-1438821340
