### ISSUE TITLE
Report stack trace in the events

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#729]
Add a new action for adding stack trace information to events

**Comment by tixxdz** [comment]
I think this should be flag not an action, and part of the tracing policy so we have more contexts per the existing actions

**Comment by kkourt** [comment]
> I think this should be flag not an action, and part of the tracing policy so we have more contexts per the existing actions

Can you please explain why? Providing an example of why using a flag versus using an action would help

**Comment by tixxdz** [comment]
By my understanding right now we generate events regardless of their actions, example: SIGKILL generates a json event ! (and it should always be the case).

Back to the context: the strack traces are useful to identify or trace back to the subsystem from where this event was generated, we can have same events that can be generated by multiple system calls or even by the kernel itself... it depends on where you hook...

1. I want to identify post, block by LSM in future, override or sigkill execve: could be user space or kernel triggered => so having the flag here and producing the trace helps regardless of the action.
2. Capability checks ditto : having the flag here also makes sense.

**Comment by kkourt** [comment]
> By my understanding right now we generate events regardless of their actions, example: SIGKILL generates a json event ! (and it should always be the case).

There are plans for a NoPost action that disables posting the event: https://github.com/cilium/tetragon/issues/730. 
The Post action is just implicit now, but there is still an action.

> 
> Back to the context: the strack traces are useful to identify or trace back to the subsystem from where this event was generated, we can have same events that can be generated by multiple system calls or even by the kernel itself... it depends on where you hook...
> 
>     1. I want to identify post, block by LSM in future, override or sigkill execve: could be user space or kernel triggered => so having the flag here and producing the trace helps regardless of the action.
> 
>     2. Capability checks ditto : having the flag here also makes sense.

Not sure I understand. How one could use the stacktrace if there is no event? The only context that the stack trace makes sense is when there is an event posted from bpf to user-space.

**Comment by tixxdz** [comment]
> > By my understanding right now we generate events regardless of their actions, example: SIGKILL generates a json event ! (and it should always be the case).
> 
> There are plans for a NoPost action that disables posting the event: #730. The Post action is just implicit now, but there is still an action.

I see, but from something that is sigkill I think we should always generate an event.. hmm 

> 
> > Back to the context: the strack traces are useful to identify or trace back to the subsystem from where this event was generated, we can have same events that can be generated by multiple system calls or even by the kernel itself... it depends on where you hook...
> > ```
> > 1. I want to identify post, block by LSM in future, override or sigkill execve: could be user space or kernel triggered => so having the flag here and producing the trace helps regardless of the action.
> > 
> > 2. Capability checks ditto : having the flag here also makes sense.
> > ```
> 
> Not sure I understand. How one could use the stacktrace if there is no event? The only context that the stack trace makes sense is when there is an event posted from bpf to user-space.

There should be event! what am I missing here? silently sigkilling without an event or context to inform users is completely broken... same for silently overriding syscalls, users can filter at different places and we already have solution for that IIRC.

Stack traces make completely sense if example: loading modules combined with sigkill, how you can tell who loaded that module user space or kernel? 

I want to sigkill or LSM fail a capability check in user namespace but also see which subsystem triggered that? how you can tell is this network, fs, ... ?

**Comment by tixxdz** [comment]
> > There should be event! what am I missing here? silently sigkilling without an event or context to inform users is completely broken... same for silently overriding syscalls, users can filter at different places and we already have solution for that IIRC.
> 
> `NoPost` will allow users to perform actions without generating an event, but that would be an option that users would have to select. By default, everything generates an event.

Ok

> 
> > Stack traces make completely sense if example: loading modules combined with sigkill, how you can tell who loaded that module user space or kernel?
> > I want to sigkill or LSM fail a capability check in user namespace but also see which subsystem triggered that? how you can tell is this network, fs, ... ?
> 
> I don't understand what you are arguing against here. If something generates an event, you will be able to get the stacktrace.

Alright, I thought this could be an action or flag of post action only. That's clear now, thanks!
