### ISSUE TITLE
Add a `NoPost` action replacing `Post` action

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#730]
It seems that when the Post action was added when creating an event was not the default behavior for all TracingPolicy. Now an event is created every time any selector matches. It would then maybe be interesting to propose a NoPost action to do the contrary, suppress the emission of an event. People might be interested in that one for performance reasons.

**Comment by tixxdz** [comment]
Here I see two use cases:
1. Real NoPost action in case we have tracingpolicies that construct context like the fd_install hooks and others in future.

2. This gives the impression we do not have enough flexible mechanisms to allow users to edit/override/nullify shipped tracing policies especially big ones... so now they are looking for the NoPost action. From performance perspectives we should not load such tracing policies in the first place, so a flexible load tracing policies from multiple files and allow users to nullify/override tracing policies by editing their /etc/tetragon/tetragon.policy.d/ files  then load everything is better than hack around NoPost...
