### ISSUE TITLE
github.com/vladimirvivien/gexe from 0.1.1 to 0.2.0

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#744]
PR: https://github.com/cilium/tetragon/pull/714

**Comment by Lan-ce-lot** [comment]
I found that `StdOut` and `StdErr` are merged to `Out` from `gexe` pkg
> https://github.com/vladimirvivien/gexe/pull/43/files#diff-7777301cba53a72cea8a0e0bb9da8691ba15cb3ff6f3b70796318165a22e0038

**Comment by Lan-ce-lot** [comment]
I will fix it.
