### ISSUE TITLE
Port amd64-only tests to arm64

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#776]
Some tests are only built on amd64 because gated by go build flags like `kprobe_amd64_test.go` for example. They might be adaptable to arm64.

**Comment by Lan-ce-lot** [comment]
I have the ARM64 environment and I'm interested in it. Could you give me more information about this？

**Comment by mtardy** [comment]
Some tests have compile flags like:

https://github.com/cilium/tetragon/blob/24e79a8ac382c8e924fdf7b51bf6a694abd03b78/pkg/sensors/tracing/kprobe_amd64_test.go#L4-L5

You can try to work on that in different steps:
1. list all the tests that have go build flags to only compile on amd64;
2. see if they can compile and run on arm64 (maybe not if they were constraints);
3. adapt the test to make them universal.

I was going to work on that at some point, but don't hesitate to try it out and explain what you did and what was the output here to advance on that.

**Comment by Lan-ce-lot** [comment]
Thanks, I'll try it.

**Comment by mtardy** [comment]
One fix was trivial https://github.com/cilium/tetragon/pull/871/commits/3faf203959914b53711250aef28ff2b1a8c28996.

To search for such files in Tetragon repo:
```shell
rg "go:build amd64" -g '!**/vendor/**'
```

However, for the other only amd64 specific test, this is less trivial:
https://github.com/cilium/tetragon/blob/1b428756133ea6b1018ad1ba1f4964f04ff67653/pkg/sensors/tracing/kprobe_amd64_test.go#L98-L100

**Comment by jrfastab** [comment]
Lets close this we've capture the spirit of this most ARM tests are run. We need LVH fix and are blocked on that file a specific issue for that if someone cares.
