### ISSUE TITLE
Local Development Guide not found.

### ISSUE THREAD

**Issue by alirazamumtaz** [cilium/tetragon#797]
The local development link needs to be fixed.
``` The 'cilium/tetragon' repository doesn't contain the 'docs/contributing/development/README.md' path in 'main.'```

**Comment by mtardy** [comment]
Yep sorry we have an issue with serving the actual website containing the doc at the moment, please find all the previous stuff here in markdown format at the moment https://github.com/cilium/tetragon/tree/main/docs/content/en/docs/contribution-guide.

**Comment by mtardy** [comment]
https://github.com/cilium/tetragon/pull/798 should fix this issue for now.
