### ISSUE TITLE
Injecting Git version into tetragon-operator binary fails

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#881]
See https://github.com/cilium/tetragon/actions/runs/4606288087/jobs/8139400747?pr=880#step:16:278 for example.

It seems that the build environment has no access to the git repository files.

**Comment by YTGhost** [comment]
Hi, I am interested in this job. Can you assign it to me?

And I don't think it is related to permissions, but possibly to this [issue](https://github.com/docker/build-push-action/issues/468). Maybe we should pass Git version information through build-args.
