### ISSUE TITLE
ci: run veristat tool on every commit

### ISSUE THREAD

**Issue by kkourt** [cilium/tetragon#892]
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/veristat.c shows stats from the verifier. It would nice if we could add it in our CI and run it per commit on every PR.

**Comment by zhy76** [comment]
Hi, I am interested in this. Can you assign it to me?

**Comment by mtardy** [comment]
Sorry it's not displayed here but I think we have Jiri from Tetragon team that wants to work on that :/

**Comment by zhy76** [comment]
> Sorry it's not displayed here but I think we have Jiri from Tetragon team that wants to work on that :/

That's great!
