### ISSUE TITLE
Write an issue template for bug report

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#894]
We could add suggestions about what commands you can run to provide good debugging context and reproducible environment, like `uname -a`, `tetra version`, etc.

**Comment by YTGhost** [comment]
Hi, I am interested in this job. Can you assign it to me?

**Comment by kkourt** [comment]
:wave: 
Wanted to add some pointers.

Please have a look at:
* tetragon's bugtool command: https://github.com/cilium/tetragon/blob/main/cmd/tetra/bugtool/bugtool.go
* Cilium's bug report issue: https://github.com/cilium/cilium/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml
* cilium-cli should work with tetragon bugtool: https://github.com/cilium/cilium-cli/pull/1035, but it would be nice if we could test it.

**Comment by YTGhost** [comment]
> bug-report-template: add an issue template for bug report #898

Ok, thanks for the pointers, I'll check it out
