### ISSUE TITLE
Get version control system information from debuginfo

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#910]
> FYI you can get vcs information from debuginfo on recent go releases: https://pkg.go.dev/runtime/debug#BuildSetting with key `vcs.revision` as far as I can tell.

_Originally posted by @lmb in https://github.com/cilium/tetragon/issues/890#issuecomment-1502941888_

This could simplify the version injection in some cases while requiring VCS to be available when building.

**Comment by lmb** [comment]
A fly in the ointment: bazel doesn't support buildinfo: https://github.com/bazelbuild/rules_go/issues/3090 Might or might not be an issue for tetragon.

**Comment by jrfastab** [comment]
I'm closing the issue. `tetra version` works today I don't see any reason to change it.
