### ISSUE TITLE
What to do if `/sys/kernel/btf` doesn't exist?

### ISSUE THREAD

**Issue by errordeveloper** [cilium/tetragon#911]
The docs currently say that most distros have `/sys/kernel/btf`, but there is nothing that explain what to do if that is not the case. Also, it'd be helpful if docs did explain what BTF actually is, as there is no explanation of that either.

Having spent some time digging around the internet, I was able to find out that there is `CONFIG_DEBUG_INFO_BTF` kernel config option, which sounds like what I should be looking for... But I've found out about that option from some very random page, and I cannot be so sure if it's all I need, or perhaps there could be more options that need checking. I have seen `CONFIG_PAHOLE_HAS_SPLIT_BTF` is another related option and I definitely have no idea what that might be for.

**Comment by mtardy** [comment]
Yep, here are some pointers on BTF requirements that we could add to explain a little bit more:
- https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere
- https://www.kernel.org/doc/html/latest/bpf/btf.html

**Comment by r21gh** [comment]
If your distro does not have BTF installed (e.g. old Ubuntu versions don't have it!) then this directory `/sys/kernel/btf/ ` would not be available. You need to build the Linux kernel with BTF. Also, setting `CONFIG_DEBUG_INFO_BTF=y` would be a part of this configuration.

Regarding the information about BTF, including @mtardy links the following could be helpful:

- [https://facebookmicrosites.github.io/bpf/blog/2018/11/14/btf-enhancement.html](https://facebookmicrosites.github.io/bpf/blog/2018/11/14/btf-enhancement.html)

**Comment by mtardy** [comment]
Yep yep indeed! Even the updated version maybe would be better:
- https://nakryiko.com/posts/btf-dedup/
