### ISSUE TITLE
cleanup: add linters on error checks and return

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#989]
After the following cleanup:
- https://github.com/cilium/tetragon/pull/976
- https://github.com/cilium/tetragon/pull/983

It would be nice to enable these linters about errors, but it will be some amount of work since they return a lots of alerts.
- errcheck (this one is particularly important)
- nilerr
- errorlint
- nilnil

We could see if we can then catch situations where we use the return value before checking the error as well.

**Comment by jrfastab** [comment]
this is old and happy with linters now. closing...
